package net.swordie.ms.handlers.header;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static net.swordie.ms.ServerConstants.*;

public enum InHeader {
    PONG(150),
    // Login Opcodes
    CONNECT_CHAT(1),
    REDISPLAY_SERVER_LIST(7),
    GUILD_CHAT(19),
    FRIEND_CHAT(20),
    GUEST_LOGIN(22),
    TOS(29),
    VIEW_SERVER_LIST(33),
    VIEW_REGISTER_PIC(50),
    VIEW_SELECT_PIC(53),
    CLIENT_FAILED(57),
    PART_TIME_JOB(59),
    CHARACTER_CARD(60),
    ENABLE_LV50_CHAR(61),
    CREATE_LV50_CHAR(62),
    ENABLE_SPECIAL_CREATION(62),
    CREATE_SPECIAL_CHAR(65),
    DUMMY_CODE(100),
    BEGIN_SOCKET(101),
    SECURITY_PACKET(102),
    PERMISSION_REQUEST(113),
    LOGIN_BASIC_INFO(114),
    CHECK_LOGIN_AUTH_INFO(115),
    VIEW_CHANNEL_REQUEST(118),
    SELECT_WORLD(119),
    CHECK_SPW_REQUEST(121),
    CHAR_SELECT(122),
    CLIENT_LOADING_TIME_LOG(123),
    CHECK_SPW_EXIST_REQUEST(124),
    MIGRATE_IN(125),
    SELECT_CHARACTER(126),
    SELECT_ACCOUNT(127),
    WORLD_INFO_REQUEST(131),
    CHECK_DUPLICATE_ID(132),
    LOGOUT_WORLD(133),
    PERMISSION_REQUEST_FAKE(134),
    CHECK_LOGIN_AUTH_INFO_FAKE(135),
    CREATE_MAPLE_ACCOUNT_FAKE(136),
    SELECT_ACCOUNT_FAKE(137),
    SELECT_WORLD_FAKE(138),
    SELECT_CHARACTER_FAKE(139),
    CREATE_NEW_CHARACTER_FAKE(140),
    CREATE_NEW_CHARACTER(141),
    DELETE_CHARACTER(144),
    RESERVED_DELETE_CHARACTER_CONFIRM(145),
    RESERVED_DELETE_CHARACTER_CANCEL(146),
    RENAME_CHARACTER(147),
    EXCEPTION_LOG(148),
    EXCEPTION_LOG_2(149),
    PRIVATE_SERVER_PACKET(153),
    RESET_LOGIN_STATE_ON_CHECK_OTP(154),
    CHANGE_SPW_REQUEST(155),
    CHECK_SOW_REQUEST_FAKE(156),
    CHECK_OTP_REQUEST(157),
    CHECK_DELETE_CHARACTER_OTP(158),
    CHECK_OTP_FOR_WEB_LAUNCHING_REQUEST(159),
    CREATE_SECURITY_HANDLE(160),
    ALBA_REQUEST(161),
    UPDATE_CHARACTER_CARD_REQUEST(162),
    AUTH_HEARTBEAT(168),
    CLIENT_ERROR(171),
    APPLIED_HOT_FIX(174),
    SERVERSTATUS_REQUEST(176),
    WVS_SET_UP_STEP(179),
    WVS_CRASH_CALLBACK(180),
    CREATE_NEW_CHARACTER_CHECKER(181),
    LOGIN_AFTER_CHAR_CREATION(184),
    CHANGE_CHARACTER_SLOT(185),
    WORLD_STATUS_REQUEST(206),
    WORLD_LIST_REQUEST(-1),
    WORLD_LEAP_REQUEST(207),
    LOGIN_INIT_CHECK(212),
    CHAR_SELECT_NO_PIC(-1),
    USE_AUTH_SERVER(192),
    AUTH_FAILURE(198),
    CHANGE_PIC_REQUEST(UnkValue),
    SPECIAL_LOGIN_AUTH_REQUEST(228),
    USER_GET_TIME_REQUEST(223),

    // Channel Opcodes
    B_E_G_I_N__U_S_E_R(247), // v265.3
    USER_TRANSFER_FIELD_REQUEST(248), // v265.3
    USER_TRANSFER_CHANNEL_REQUEST(249), // v265.3
    USER_TRANSFER_TO_HUB_REQUEST(250), // v265.3
    WORLD_TRANSFER_REQUEST(251), // v265.3
    WORLD_TRANSFER_SHINNING_STAR_REQUEST(252), // v265.3
    USER_MIGRATE_TO_CASH_SHOP_REQUEST(253), // v265.3
    USER_MIGRATE_TO_AUCTION_HOUSE_REQUEST(254), // v265.3
    USER_MIGRATE_TO_PVP_REQUEST(255), // v265.3
    PARTY_MIGRATE_TO_PVP_REQUEST(256), // v265.3
    USER_REQUEST_PVP_STATUS(257), // v265.3
    USER_MIGRATE_TO_PVE_REQUEST(258), // v265.3
    USER_MIGRATE_TO_UNK_REQUEST(259), // v265.3
    USER_MOVE(260), // v265.3
    USER_SIT_REQUEST(261), // v265.3
    USER_PORTABLE_CHAIR_SIT_REQUEST(262), // v265.3
    USER_UNK_REQUEST(263), // v265.3
    USER_ON_STAGE_ITEM_USE_REQUEST(264), // v265.3
    USER_EMOTION_ITEM_USE_REQUEST(265), // v265.3
    USER_DANCE_STOP_REQUEST(266), // v265.3
    USER_MELEE_ATTACK(267), // v265.3
    USER_SHOOT_ATTACK(268), // v265.3
    USER_MAGIC_ATTACK(269), // v265.3
    USER_BODY_ATTACK(270), // v265.3
    USER_AREA_DOT_ATTACK(271), // v265.3
    USER_MOVING_SHOOT_ATTACK_PREPARE(272), // v265.3
    USER_AFFECTED_AREA_FOR_SCREEN_ATTACK(273), // v265.3
    USER_UNK_ATTACK(274), // v265.3
    USER_HIT(275), // v265.3
    USER_ATTACK_USER(276), // v265.3
    USER_CHAT(277), // v265.3
    USER_ITEM_LINKED_CHAT(278), // v265.3
    USER_AD_BOARD_CLOSE(279), // v265.3
    USER_EMOTION(280), // v265.3
    ANDROID_EMOTION(281), // v265.3
    USER_ACTIVATE_EFFECT_ITEM(282), // v265.3
    USER_MONKEY_EFFECT_ITEM(283), // v265.3
    USER_ACTIVATE_NICK_ITEM(284), // v265.3
    USER_ACTIVATE_DAMAGE_SKIN(UnkValue),
    USER_ACTIVATE_DAMAGE_SKIN_PREMIUM(UnkValue),
    USER_DAMAGE_SKIN_SAVE_REQUEST(288), // v265.3
    USER_CHANGE_CUSTOMIZED_BACKGROUND_REQUEST(289), // v265.3
    USER_DEFAULT_WING_ITEM(290), // v265.3
    USER_KAISER_TRANSFORM_WING(291), // v265.3
    USER_KAISER_TRANSFORM_TAIL(292), // v265.3
    USER_UPGRADE_TOMB_EFFECT(293), // v265.3
    USER_BAN_MAP_BY_MOB(294), // v265.3
    USER_MONSTER_BOOK_SET_COVER(295), // v265.3
    USER_SELECT_NPC(296), // v265.3
    USER_SCRIPT_MESSAGE_ANSWER(297), // v265.3
    USER_SHOP_REQUEST(299), // v265.3
    USER_TRUNK_REQUEST(300), // v265.3
    USER_ENTRUSTED_SHOP_REQUEST(301), // v265.3
    USER_TRUNK_GETALL_REQUEST(302), // v265.3
    USER_EFFECT_LOCAL(303), // v265.3
    USER_FINAL_ATTACK_REQUEST(304), // v265.3
    USER_CREATE_AREA_DOT_REQUEST(305), // v265.3
    USER_AREA_EXPLOSION_REQUEST(306), // v265.3
    USER_CREATE_HOLIDOM_REQUEST(307), // v265.3
    REQ_MAKING_SKILL_EFF(308), // v265.3
    AUCTION_HOUSE_REQUEST(310), // v265.3
    AUCTION_LEAVE_REQUEST(311), // v265.3
    ADMIN_SHOP_REQUEST(313), // v265.3
    USER_GATHER_ITEM_REQUEST(314), // v265.3
    USER_SORT_ITEM_REQUEST(315), // v265.3
    USER_CHANGE_SLOT_POSITION_REQUEST(316), // v265.3
    USER_TEXT_EQUIP_INFO(317), // v265.3
    USER_POP_OR_PUSH_BAG_ITEM_TO_INVEN(318), // v265.3
    USER_BAG_TO_BAG_ITEM(319), // v265.3
    USER_POUR_IN_BAG_TO_BAG(320), // v265.3
    USER_POUR_IN_BAG_TO_BAG_2(321), // v265.3
    USER_POUR_IN_BAG_TO_BAG_3(322), // v265.3
    USER_STAT_CHANGE_ITEM_USE_REQUEST(323), // v265.3
    USER_STAT_CHANGE_ITEM_CANCEL_REQUEST(324), // v265.3
    USER_STAT_CHANGE_BY_PORTABLE_CHAIR_REQUEST(325), // v265.3
    USER_MOB_SUMMON_ITEM_USE_REQUEST(326), // v265.3
    USER_PET_FOOD_ITEM_USE_REQUEST(327), // v265.3
    USER_TAMING_MOB_FOOD_ITEM_USE_REQUEST(328), // v265.3
    USER_SCRIPT_ITEM_USE_REQUEST(329), // v265.3
    USER_RECIPE_OPEN_ITEM_USE_REQUEST(330), // v265.3
    USER_CONSUME_CASH_ITEM_USE_REQUEST(331), // v265.3
    USER_ADDITIONAL_SLOT_EXTEND_ITEM_USE_REQUEST(332), // v265.3
    USER_CASH_PET_PICK_UP_ON_OFF_REQUEST(333), // v265.3
    USER_CASH_PET_SKILL_SETTING_REQUEST(334), // v265.3
    USER_DESTROY_PET_ITEM_REQUEST(335), // v265.3
    USER_BRIDLE_ITEM_USE_REQUEST(336), // v265.3
    USER_SKILL_LEARN_ITEM_USE_REQUEST(337), // v265.3
    USER_SKILL_RESET_ITEM_USE_REQUEST(UnkValue),
    USER_ABILITY_RESET_ITEM_USE_REQUEST(338), //  v265.3
    USER_ABILITY_CHANGE_ITEM_USE_REQUEST(339), //  v265.3
    USER_EXP_CONSUME_ITEM_USE_REQUEST(340), //  v265.3
    USER_EXP_ITEM_GET_REQUEST(341), // v265.3
    USER_CHAR_SLOT_INC_ITEM_USE_REQUEST(342), // v265.3
    USER_KAISER_COLOR_CHANGE_ITEM_USE_REQUEST(343), // v265.3
    USER_MEGA_BURNINATOR_ITEM_USE_REQUEST(344), // v265.3
    USER_MAP_TRANSFER_ITEM_USE_REQUEST(346), // v265.3
    USER_PORTAL_SCROLL_USE_REQUEST(347), // v265.3
    USER_FIELD_TRANSFER_REQUEST(348), // v265.3
    USER_FIELD_TRANSFER_REQUEST_2(349), // v265.3
    USER_UPGRADE_ITEM_USE_REQUEST(350), // v265.3
    USER_UPGRADE_ASSIST_ITEM_USE_REQUEST(351), // v265.3
    USER_HYPER_UPGRADE_ITEM_USE_REQUEST(352), // v265.3
    USER_MEMORIAL_EX_UPGRADE_ITEM_USE_REQUEST(353), // v265.3
    USER_MEMORIAL_EX_UPGRADE_ITEM_OPTION_REQUEST(354), // v265.3
    USER_KARMA_CONSUME_ITEM_USE_REQUEST(355), // v265.3
    USER_EVENT_UPGRADE_ITEM_USE_REQUEST(356), // v265.3
    USER_ITEM_OPTION_UPGRADE_ITEM_USE_REQUEST(357), // v265.3
    USER_ADDITIONAL_OPT_UPGRADE_ITEM_USE_REQUEST(358), // v265.3

    USER_ITEM_SLOT_EXTEND_ITEM_USE_REQUEST(363), // v265.3
    USER_WEAPON_TEMP_ITEM_OPTION_REQUEST(364), // v265.3
    USER_ITEM_SKILL_SOCKET_UPGRADE_ITEM_USE_REQUEST(365), // v265.3
    USER_ITEM_SKILL_OPTION_UPGRADE_ITEM_USE_REQUEST(366), // v265.3
    USER_CONSUME_CUBE_ITEM_USE_REQUEST(367), // v265.3
    USER_BONUS_MYSTICAL_ITEM_USE_REQUEST(368), // v265.3
    USER_BONUS_BRIGHT_CUBE_ITEM_USE_REQUEST(369), // v265.3

    USER_EQUIPMENT_ENCHANT_WITH_SINGLE_UI_REQUEST(371), // v265.3

    USER_UI_ARCANE_SYMBOL_ENCHANCE_REQUEST(374), // v265.3
    USER_UI_SACRED_SYMBOL_ENCHANCE_REQUEST(375), // v265.3
    USER_UI_OPEN_ITEM_USE_REQUEST(376), // v265.3
    USER_DAMAGE_METER_ITEM_REQUEST(377), // v265.3
    USER_BAG_ITEM_USE_REQUEST(378), // v265.3
    USER_ITEM_RELEASE_REQUEST(379), // v265.3
    USER_LOCK_SORT_ITEM_REQUEST(380), // v265.3
    USER_MEMORIAL_CUBE_OPTION_REQUEST(UnkValue),
    USER_MIRACLE_CIRCULATOR_OPTION_REQUEST(383), // v265.3
    USER_TOADS_HAMMER_REQUEST(385), // v265.3
    USER_TOADS_HAMMER_HELP_REQUEST(386), // v265.3
    USER_RENT_ITEM_REQUEST(387), // v265.3
    USER_RENT_ITEM_RESULT(388), // v265.3
    USER_CHANGE_SOUL_COLLECTION_REQUEST(UnkValue),
    USER_SELECT_SOUL_SKILL_UP_REQUEST(UnkValue),
    USER_ABILITY_UP_REQUEST(393), // v265.3
    USER_ABILITY_MASS_UP_REQUEST(394), // v265.3
    USER_DOT_HEAL(395), // v265.3
    USER_CHANGE_STAT_REQUEST(396), // v265.3
    USER_CHANGE_STAT_REQUEST_BY_ITEM_OPTION(397), // v265.3
    USER_SKILL_UP_REQUEST(398), // v265.3
    USER_DROP_MONEY_REQUEST(399), // v265.3
    USER_GIVE_POPULARITY_REQUEST(400), // v265.3
    USER_GIVE_POPULARITY_REQUEST_2(401), // v265.3
    USER_PARTY_REQUEST(402), // v265.3
    USER_ACTIVATE_PET_REQUEST(403), // v265.3
    USER_REGISTER_PET_AUTO_BUFF_REQUEST(404), // v265.3
    USER_CHECK_TEMPORARY_STAT_DURATION_REQUEST(405), // v265.3
    USER_PORTAL_SCRIPT_REQUEST(406), // v265.3
    USER_PORTAL_SCRIPT_REQUEST_2(407), // v265.3
    USER_PORTAL_SCRIPT_REQUEST_3(408), // v265.3
    USER_PORTAL_TELEPORT_REQUEST(409), // v265.3
    USER_CALLING_TELEPORT_REQUEST(410), // v265.3
    USER_MAP_TRANSFER_REQUEST(411), // v265.3

    USER_ANTI_MACRO_ITEM_USE_REQUEST(UnkValue),
    USER_ANTI_MACRO_SKILL_USE_REQUEST(UnkValue),
    USER_ANTI_MACRO_REFRESH_REQUEST(UnkValue),

    USER_CLAIM_REQUEST(413), // v265.3
    USER_QUEST_REQUEST(414), // v265.3
    USER_MEDAL_REISSUE_REQUEST(415), // v265.3
    USER_CALC_DAMAGE_STAT_SET_REQUEST(416), // v265.3
    USER_B2_BODY_REQUEST(417), // v265.3
    USER_THROW_GRENADE(418), // v265.3
    USER_DESTROY_GRENADE(419), // v265.3
    USER_CREATE_AURA_BY_GRENADE(420), // v265.3
    USER_SET_MOVE_GRENADE(421), // v265.3
    USER_SET_MOVE_GRENADE_2(422), // v265.3
    USER_SET_HOWLING_GALE(423), // v265.3
    USER_MACRO_SYS_DATA_MODIFIED(424), // v265.3
    USER_SKILL_SEQUENCE_SKILLS_REQUEST(425), // v265.3
    USER_SKILL_SEQUENCE_BUFFS_REQUEST(426), // v265.3

    USER_SELECT_NPC_ITEM_USE_REQUEST(428), // v265.3
    USER_LOTTERY_ITEM_USE_REQUEST(429), // v265.3
    USER_ROULETTE_START_REQUEST(430), // v265.3
    USER_ROULETTE_RESULT_REQUEST(431), // v265.3
    USER_ITEM_MAKE_REQUEST(432), // v265.3
    USER_CLIENT_TIMER_END_REQUEST(433), // v265.3
    USER_CLIENT_RESOLUTION_REQUEST(434), // v265.3
    USER_FOLLOW_CHARACTER_REQUEST(435), // v265.3
    USER_FOLLOW_CHARACTER_WITHDRAW(436), // v265.3
    SET_PASSENGER_RESULT(437), // v265.3
    USER_REQUEST_INSTANCE_TABLE(438), // v265.3
    USER_REQUEST_RESPAWN(439), // v265.3
    USER_CONSUME_HAIR_ITEM_USE_REQUEST(440), // v265.3
    USER_FORCE_ATOM_COLLISION(442), // v265.3
    USER_DEBUFF_OBJ_COLLISION(443), // v265.3
    USER_CREATE_LUCK_OF_THE_DRAW_FORCE_ATOM(445), // v265.3
    USER_UPDATE_BENEDICTION_AREA(446), // v265.3
    USER_UPDATE_LAPIDIFICATION(447), // v265.3
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET(449), // v265.3
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_VALUE_SET(450), // v265.3
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET_UI(451), // v265.3
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_CHANGE_PRESET(452), // v265.3
    USER_REQUEST_OCCUMPATION_DATA(453), // v265.3
    USER_KEY_DOWN_AREA_MOVING(454), // v265.3
    USER_CHECK_WEDDING_EX_REQUEST(455), // v265.3
    USER_CATCH_DEBUFF_COLLISION(456), // v265.3
    USER_AFFECTED_AREA_CREATED(457), // v265.3
    USER_AFFECTED_AREA_REMOVED(458), // v265.3
    USER_DAZZLE_HIT(459), // v265.3
    USER_MESO_EXCHANGE_REQUEST(462), // v265.3
    INVITE_CHAIR(464), // v265.3
    RESULT_CHAIR(465), // v265.3
    ZERO_TAG(468), // v265.3
    ZERO_SHARE_CASH_EQUIP_PART(469), // v265.3
    ZERO_LAST_ASSIST_STATE(470), // v265.3
    USER_SHOOT_ATTACK_IN_FPS(471), // v265.3
    USER_LUCKY_ITEM_USE_REQUEST(472), // v265.3
    USER_MOB_MOVE_ABILITY_CHANGE(473), // v265.3
    USER_DRAGON_ACTION(474), // v265.3
    USER_DRAGON_BREATH_EARTH_EFFECT(475), // v265.3
    USER_RENAME_RESULT(476), // v265.3
    USER_RENAME_REQUEST(477), // v265.3
    NOTICE_COMMAND(478), // v265.3
    GROUP_MESSAGE(479), // v265.3
    ITEM_LINKED_GROUP_MESSAGE(480), // v265.3
    FIELD_UNIVERSE_MESSAGE(481), // v265.3
    WHISPER(482), // v265.3
    WHISPER_ITEM(483), // v265.3
    MESSENGER(484), // v265.3
    MINI_ROOM(485), // v265.3
    PARTY_REQUEST(487), // v265.3
    PARTY_RESULT(488), // v265.3
    PARTY_INVITABLE_SET(489), // v265.3
    EXPEDITION_REQUEST(UnkValue),
    PARTY_ADVER_REQUEST(UnkValue),
    URUS_PARTY_REQUEST(UnkValue), // Dùng URSUS_PARTY_REQUEST
    GUILD_REQUEST(UnkValue),
    GUILD_RESULT(UnkValue),
    GUILD_JOIN_REQUEST(UnkValue),
    GUILD_JOIN_CANCEL_REQUEST(UnkValue),
    GUILD_JOIN_ACCEPT(UnkValue),
    GUILD_JOIN_REJECT(UnkValue),
    GUILD_CONTENT_RANK_REQUEST(UnkValue),
    TOWER_RANK_REQUEST(UnkValue),
    ADMIN(502), // v265.3
    LOG(503), // v265.3
    LOG2(504), // v265.3
    FRIEND_REQUEST(505), // v265.3
    LOAD_ACCOUNT_ID_OF_CHARACTER_FRIEND_REQUEST(UnkValue),
    MEMO_REQUEST(UnkValue),
    MEMO_FLAG_REQUEST(UnkValue),
    ENTER_TOWN_PORTAL_REQUEST(511), // v265.3
    ENTER_RANDOM_PORTAL_REQUEST(512), // v265.3
    ENTER_OPEN_GATE_REQUEST(513), // v265.3
    SLIDE_REQUEST(UnkValue),
    FUNC_KEY_MAPPED_MODIFIED(516), // v265.3

    LINK_SKILL_REQUEST(518), // v265.3

    R_P_S_GAME(UnkValue),
    G_S_R_P_S_GAME(UnkValue),
    STAR_PLANET__G_S_R_P_S_GAME(UnkValue),
    G_S_R_P_S_FORCE_SELECT(UnkValue),
    MARRIAGE_REQUEST(UnkValue),
    WEDDING_WISH_LIST_REQUEST(UnkValue),
    GUEST_BLESS(UnkValue),
    BOOBY_TRAP_ALERT(UnkValue),
    ALLIANCE_REQUEST(UnkValue),
    ALLIANCE_RESULT(UnkValue),
    TALK_TO_TUTOR(UnkValue),
    TALK_TO_PARTNER(UnkValue),
    USER_SWITCH_R_P(UnkValue),
    REQUEST_INC_COMBO(UnkValue),
    REQUEST_DEC_COMBO(UnkValue),

    REQUEST_SET_BLESS_OF_DARKNESS(524), // v263
    REQUEST_SET_HP_BASE_DAMAGE(525), // v263
    REQUEST_MATRIX_SUMMON_ATTACK(526), // v263
    SHADOW_SPEAR_REQUEST(527), // v263

    MOB_CRC_DATA_RESULT(534), // v265.3
    MAKING_SKILL_REQUEST(536), // v265.3
    BROADCAST_EFFECT_TO_SPLIT(537), // v265.3
    BROADCAST_ONE_TIME_ACTION_TO_SPLIT(538), // v265.3
    BROADCAST_AFFECTED_EFFECT_TO_SPLIT(539), // v265.3
    DEBUG_ONLY_COMMAND(540), // v265.3
    MICRO_BUFF_END_TIME(542), // v265.3
    REQUEST_SESSIVALUE(543), // v265.3
    USER_TRANSFER_FREE_MARKET_REQUEST(UnkValue), // v265.3 REMOVED
    USER_REQUEST_SET_STEAL_SKILL_SLOT(544), // v265.3
    USER_REQUEST_STEAL_SKILL_MEMORY(545), // v265.3
    USER_REQUEST_STEAL_SKILL_LIST(546), // v265.3
    USER_REQUEST_STEAL_SKILL(547), // v265.3
    RECALL_SUMMON(548), // v265.3
    REWARD_MOB_LIST_RESULT(550), // v265.3
    USER_LV_UP_GUIDE_NOTICE(551), // v265.3
    USER_EQUIP_SLOT_LEVEL_MINUS_ITEM_USE_REQUEST(552), // v265.3
    USER_REQUEST_FLYING_SWORD_START(553), // v265.3
    USER_REQUEST_FLYING_SWORD_END(554), // v265.3
    BOARD_GAME_REQUEST(555), // v265.3
    BINGO_REQUEST(556), // v265.3
    BINGO_CASSANDRA_REQUEST(557), // v265.3
    ACTION_BAR_REQUEST(558), // v265.3
    USER_REQUEST_SET_OFF_TRINITY(559), // v265.3
    MESO_RANGER_REQUEST(559), // v265.3
    USER_REQUEST_SET_SMASH_COUNT(560), // v265.3
    USER_HYPER_SKILL_UP_REQUEST(561), // v265.3
    USER_HYPER_SKILL_RESET_REQUEST(562), // v265.3
    USER_HYPER_STAT_UP_REQUEST(563), // v265.3
    USER_HYPER_STAT_RESET_REQUEST(564), // v265.3
    USER_HYPER_STAT_CHANGE_PRESET_REQUEST(565), // v265.3
    USER_SET_DRESS_CHANGED_REQUEST(566), // v265.3
    ENTRY_RECORD_REQUEST(567), // v265.3
    SET_MAX_GAUGE(568), // v265.3
    USER_RETURN_EFFECT_RESPONSE(569), // v265.3
    GET_SERVER_TIME(UnkValue),
    GET_CHARACTER_POSITION(UnkValue),
    USER_REQUEST_CHANGE_MOB_ZONE_STATE(UnkValue),
    USER_REQUEST_JEWEL_CRAFT(UnkValue),
    EVOLVING_REQUEST(UnkValue),
    USER_MIXER_REQUEST(UnkValue),
    SUMMON_EVENT_REWARD(UnkValue),
    MYSTIC_FIELD_MOVE(UnkValue),
    YUT_GAME_REQUEST(UnkValue),
    USER_JEWEL_CRAFT_REQUEST(UnkValue),
    VALUE_PACK_REQUEST(UnkValue),
    REQUEST_RELOGIN_COOKIE(579), // v265.3
    WAIT_QUEUE_REQUEST(UnkValue),
    CHECK_TRICK_OR_TREAT_REQUEST(UnkValue),
    HALLOWEEN_CANDY_RANKING_REQUEST(UnkValue),
    GET_REWARD_REQUEST(UnkValue),
    MAPLE_STYLE_BONUS_REQUEST(UnkValue),
    MAPLE_STYLE_ADVICE_REQUEST(UnkValue),
    MAPLE_STYLE_SET_SCORE_REQUEST(UnkValue),
    MENTORING(UnkValue),
    GET_LOTTERY_RESULT(UnkValue),
    ROOTABYSS_ENTER_REQUEST(UnkValue),
    USER_SET_ITEM_ACTION(UnkValue),
    USER_SET_BITS_CASE(UnkValue),
    USER_SET_BITS_SLOT(UnkValue),
    USER_ANTI_MACRO_QUESTION_RESULT(UnkValue),
    USER_PINKBEAN_ROLLING(UnkValue),
    USER_PINKBEAN_YO_YO_STACK_REQUEST(UnkValue),
    USER_CHARGE_WIND_ENERGY_REQUEST(UnkValue),
    USER_QUICK_MOVE_SCRIPT(594), // v265.3
    TIME_GATE_REQUEST(595), // v265.3
    USER_ANDROID_SHOP(596), // v265.3
    USER_COMPLETE_NPC_SPEECH(597), // v265.3
    USER_COMPLETE_ANOTHER_USER_CHECK(598), // v265.3
    USER_COMPLETE_COMBO_KILL_COUNT_CHECK(599), // v265.3
    USER_COMPLETE_MULTI_KILL_CHECK(600), // v265.3
    USER_COMPLETE_MULTI_KILL_COUNT_CHECK(601), // v265.3
    USER_DAMAGE_FALLING_CHECK(UnkValue),
    USER_COMPLETE_PERSONAL_SHOP_BUY_CHECK(UnkValue),
    USER_DAILY_COMMITMENT_CHECK(UnkValue),
    USER_MOB_DROP_MESO_PICKUP(UnkValue),
    USER_BREAK_TIME_FIELD_ENTER(UnkValue),
    USER_RUN_ACT_QUEST(UnkValue),
    JOURNAL_AVATAR_REQUEST(UnkValue),

    REQUEST_EVENT_LIST(609), // v265.3
    USER_SIGN_REQUEST(610), // v265.3
    ADD_ATTACK_RESET(611), // v265.3
    SET_EVENT_NAME_TAG(612), // v265.3
    SOMETHING_WITH_ABILITY_RESET(UnkValue),
    USER_AFFECTED_AREA_REMOVE_BY_TIME(UnkValue),
    USER_AFFECTED_AREA_REMOVE_BY_REASON(UnkValue),
    JOB_FREE_CHANGE_REQUEST(620), // v265.3
    LIBRARY_START_SCRIPT(621), // v265.3
    CHANNEL_USER_COUNT_REQUEST(UnkValue),
    UN_URUS_SELECTED_SKILL_LIST(UnkValue),
    SOUL_DUNGESYS(UnkValue),
    USER_COORDINATION_CONTEST_REQUEST(UnkValue),
    USER_SOUL_EFFECT_REQUEST(625), // v265.3
    USER_SPIN_OFF_NEW_MODIFY_REQUEST(UnkValue),
    BLACK_LIST(UnkValue),
    SKILL_HELPER_POPUP(UnkValue),
    BLOCKBUSTER(UnkValue),
    M_TALK_OFFLINE_ACCOUNT_FRIENDS_NAME_REQUEST(UnkValue),
    CHARACTER_BURNING(UnkValue),
    UPDATE_CHARACTER_SELECT_LIST(UnkValue),
    DIRECT_GO_TO_FIELD(UnkValue),
    TRY_REGISTER_TELEPORT(UnkValue),
    USER_TOWER_CHAIR_SETTING(UnkValue),
    USER_LAST_COLLECT_MONSTER_RESET(UnkValue),
    END_OVER_HEAT(UnkValue),
    UNION_REQUEST(639), // v265.3
    TRADE_KING_SHOP_REQ(UnkValue),
    TRADE_KING_SHOP_INFO_REQ(UnkValue),
    KEY_DOWN_SKILL_COST(650), // v265.3
    RW_LIFT_PRESS_REQUEST(UnkValue),
    UPDATE_MATRIX(658), // v265.3
    NODE_STONE_CRAFTING(661), // v265.3
    UPDATE_ARK_SPECTRA_ENERGY(663), // v265.3
    USER_REVIVE_IN_BOSS_INSTANCE(665), // v265.3
    GREATER_DARK_SERVANT_SWAP_REQUEST(UnkValue),
    INHUMAN_SPEED_FORCE_ATOM_REQUEST(668), // v265.3
    CRYSTAL_SKILL_REQUEST(670), // v265.3
    AFFECTED_AREA_UPDATE(UnkValue),

    USER_CHARACTER_INFO_SELF_REQUEST(695), // v265.3
    USER_CHARACTER_INFO_REQUEST(696), // v265.3
    USER_CHARACTER_PRESET_MODIFIED(698), // v265.3
    BOSS_UI_REQUEST(700), // v265.3
    MONSTER_PARK_UI_REQUEST(703), // v265.3

    B_E_G_I_N__P_E_T(711), // v265.3
    PET_MOVE(712), // v265.3
    PET_ACTION(713), // v265.3
    PET_INTERACTION_REQUEST(714), // v265.3
    PET_DROP_PICK_UP_REQUEST(715), // v265.3
    PET_STAT_CHANGE_ITEM_USE_REQUEST(716), // v265.3
    PET_UPDATE_EXCEPTION_LIST_REQUEST(717), // v265.3
    PET_FOOD_ITEM_USE_REQUEST(718), // v265.3
    PET_OPEN_SHOP(719), // v265.3
    E_N_D__P_E_T(720), // v265.3

    B_E_G_I_N__S_K_I_L_L_P_E_T(721), // v265.3
    SKILL_PET_MOVE(722), // v265.3
    SKILL_PET_ACTION(723), // v265.3
    SKILL_PET_STATE(724), // v265.3
    SKILL_PET_DROP_PICK_UP_REQUEST(725), // v265.3
    SKILL_PET_UPDATE_EXCEPTION_LIST_REQUEST(726), // v265.3
    E_N_D__S_K_I_L_L_P_E_T(727), // v265.3

    B_E_G_I_N__S_U_M_M_O_N_E_D(728), // v265.3
    SUMMONED_MOVE(729), // v265.3
    SUMMONED_ATTACK(730), // v265.3
    SUMMONED_HIT(731), // v265.3
    SUMMONED_SKILL(732), // v265.3
    SUMMONED_CREATE_SHOOT_OBJ(733), // v265.3
    SUMMONED_REMOVE(734), // v265.3
    SUMMONED_ATTACK_PVP(735), // v265.3
    SUMMONED_HEXA_CRYSTAL_SKILL_DEUS(736), // v265.3
    SUMMONED_ATTACK_TO_TARGET_MOB(737), // v265.3
    SUMMONED_ACTION(738), // v265.3
    SUMMONED_ASSIST_ATTACK_DONE(739), // v265.3
    SUMMONED_SKILL_ATTACK(740), // v265.3
    SUMMONED_SEQUENCE_ATTACK(741), // v265.3
    SUMMONED_APOCALYPSE_CANNON_REQUEST(742), // v265.3
    SUMMONED_ELEMENTAL_FURY_REQUEST(743), // v265.3
    SUMMONED_MECHA_CARRIER_REQUEST(744), // v265.3
    SUMMONED_UNK(745), // v265.3
    E_N_D__S_U_M_M_O_N_E_D(746), // v265.3

    B_E_G_I_N__D_R_A_G_O_N(747), // v265.3
    DRAGON_MOVE(748), // v265.3
    DRAGON_GLIDE(749), // v265.3
    E_N_D__D_R_A_G_O_N(750), // v265.3

    B_E_G_I_N__A_N_D_R_O_I_D(751), // v265.3
    ANDROID_MOVE(752), // v265.3
    ANDROID_ACTION_SET(753), // v265.3
    E_N_D__A_N_D_R_O_I_D(754), // v265.3

    B_E_G_I_N__F_O_X_M_A_N(755), // v265.3
    FOX_MAN_MOVE(756), // v265.3
    FOX_MAN_ACTION_SET_USE_REQUEST(757), // v265.3
    E_N_D__F_O_X_M_A_N(758), // v265.3

    PASSIVESKILL_INFO_UPDATE(UnkValue),
    UPDATE_CLIENT_ENVIRONMENT(UnkValue),
    USER_LASER_INFO_FOR_REMOTE(UnkValue),
    DIRECTION_NODE_COLLISION(UnkValue),
    RETURN_TELEPORT_DEBUFF(UnkValue),
    CHECK_PROCESS(UnkValue),
    MEMO_IN_GAME_REQUEST(UnkValue),
    EGO_EQUIP_GAUGE_COMPLETE_RETURN(UnkValue),
    EGO_EQUIP_CREATE_UPGRADE_ITEM(UnkValue),
    EGO_EQUIP_CREATE_UPGRADE_ITEM_COST_REQUEST(UnkValue),
    EGO_EQUIP_TALK_REQUEST(UnkValue),
    EGO_EQUIP_CHECK_UPDATE_ITEM_REQUEST(UnkValue),
    EGO_EQUIP_GROWTH_REQUEST(UnkValue),
    INHERITANCE_INFO_REQUEST(UnkValue),
    INHERITANCE_UPGRADE_REQUEST(UnkValue),
    MIRROR_READING_SELECT_BOOK_REQUEST(UnkValue),
    MAPLE_CHAT_REQUEST(UnkValue),
    LIKE_POINT(UnkValue),
    LEVEL_UP_GUIDE_REQUEST(788), // v265.3
    USER10TH_STREAMING_URL_REQUEST(UnkValue),
    USER_UPDATE_MAPLE_TV_SHOW_TIME_REQUEST(UnkValue),
    REDUCE_DOT_DAMGE_BASE_BUFF_REQUEST(UnkValue),
    MIRROR_STUDY_COMPLETE(UnkValue),
    REQUEST_ARROW_PLATTER_OBJ(792), // v265.3
    USER_TIME_EVENT_UI_OPEN_REQUEST(UnkValue),
    USER_TIME_EVENT_RESULT_REQUEST(UnkValue),
    USER_TIME_EVENT_COMPLETE_REQUEST(UnkValue),
    USER_TIME_EVENT_PASSED_TIME_SET(UnkValue),
    INVASION_SETTING_REQUEST(UnkValue),
    USER_FIELD_ATTACK_OBJ_REQUEST_BOARDING(UnkValue),
    USER_FIELD_ATTACK_OBJ_REQUEST_GET_OFF(UnkValue),
    MONSTER_BATTLE(UnkValue),
    BOSS_ARENA_MATCH_REQUEST(UnkValue),
    BOSS_ARENA_MIGRATE_REQUEST(UnkValue),
    MOB_USER_CONTROL_SKILL_Q_PUSH(UnkValue),
    MOB_USER_CONTROL_SKILL_Q_POP(UnkValue),
    MOB_USER_CONTROL_SKILL_FORCED_Q_POP(UnkValue),
    PARTY_QUEST_RANKING_REQUEST(UnkValue),
    ATTENDANCE_EVENT(UnkValue),
    ATTENDANCE_EVENT_REWARD_REQ(UnkValue),
    UI_ATTENDANCE_GHOST_CHANGE_REQ(UnkValue),
    EVENT_UI_REQ(UnkValue),
    ATTENDANCE_EVENT_SELECT_REWARD(UnkValue),
    USER_SET_CUSTOMIZE_EFFECT(815), // v265.3
    USER_CUSTOMIZE_EFFECT_ITEM_MODIFY(816), // v265.3
    USER_GROWTH_HELPER_REQUEST(817), // v265.3
    USER_CONTENTS_MAP_REQUEST(818), // v265.3
    USER_TIMER_REQ(819), // v265.3
    USER_MANNEQUIN(820), // v265.3
    USER_BUFFER_FLY_REQ(821), // v265.3
    USER_NON_TARGET_FORCE_ATOM_ATTACK(822), // v265.3
    USER_RUN_SCRIPT(823), // v265.3
    USER_SHADOW_MOMENTUM_REQUEST(824), // v265.3

    CHECK_BOSS_PARTY_BY_SCRIPT(833), // v265.3

    MONSTER_COLLECTION_COMPLETE_REWARD_REQ(UnkValue),
    MONSTER_COLLECTION_EXPLORE_REQ(UnkValue),
    PLAT_FORMAR_ENTER_REQUEST(834), // v265.3
    STIGMA_DELEVERY_REQUEST(835), // v265.3
    CORRUPTION_REQUEST(836), // v265.3
    UNION_RAID_RETREAT(837), // v265.3
    DREAM_BREAKER_SKILL(UnkValue),
    SPECIAL_GAME_EXIT(UnkValue),

    QUICK_MOVE_NAVIGATION_REQUEST(842), // v265.3
    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P(UnkValue),
    INVITATION_ACCEPT_USER(UnkValue),
    INVITATION_CANCEL_USER(UnkValue),
    EVENT_GROUP_LEAVE(UnkValue),
    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(UnkValue),
    E_N_D__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(UnkValue),
    E_N_D__E_V_E_N_T__G_R_O_U_P(UnkValue),

    B_E_G_I_N__E_V_E_N_T__R_A_N_K_I_N_G(UnkValue),
    EVENT_RANKING_OPEN(UnkValue),
    EVENT_RANKING_HELP(UnkValue),
    E_N_D__E_V_E_N_T__R_A_N_K_I_N_G(UnkValue),

    B_E_G_I_N__A_F_R_E_E_C_A_T_V(UnkValue),
    AFREECA_TV_BROAD_START(UnkValue),
    AFREECA_TV_BROAD_STOP(UnkValue),
    E_N_D__A_F_R_E_E_C_A_T_V(UnkValue),

    USER_SURVEY_REQUEST(UnkValue),
    GAME_EXIT(UnkValue),
    USER_SAVAGE_FLAME_REQUEST(613), // v265.3
    USER_FLAME_ORB_REQUEST(614), // v265.3
    USER__SAD_RESULT_UI__CLOSE(UnkValue),
    FREE_LOOK_CHANGE_REQUEST(UnkValue),
    FREE_LOOK_CHANGE_UI_OPEN_FAILED(UnkValue),
    USER_SMART_PHONE_CALL_REQUEST(UnkValue),
    USER_JAGUAR_CHANGE_REQUEST(UnkValue),
    FPS_LOG(UnkValue),
    PACKET_MODIFY_LOG(UnkValue),
    DYNAMIC_OBJECT_VISIBLE_REQUEST(UnkValue),

    USER_SPECIAL_EXIT(845), // v265.3

    BATTLE_USER_AVATAR_SELECT(UnkValue),
    BATTLE_USER_ATTACK(UnkValue),
    BATTLE_USER_ATTACK_EXPIRE(UnkValue),
    BATTLE_USER_ATTACK_POSITION(UnkValue),
    BATTLE_USER_HIT(UnkValue),
    BATTLE_USER_HIT_BY_MOB(UnkValue),
    BATTLE_STAT_CORE_REQUEST(UnkValue),
    BATTLE_USER_ALIVE(UnkValue),
    USER_CONTENTS_BOOK_REQUEST(UnkValue),
    PERFORMANCE_CLIENT_LOGIN(UnkValue),
    PERFORMANCE_CLIENT_IN_FIELD(UnkValue),
    PING_CHECK_REQUEST__CLIENT_TO_GAME(UnkValue),
    PING_CLIENT_TO_GAME(UnkValue),
    PLANT_POT_CLICK(UnkValue),
    RANDOM_MISSION_REQUEST(UnkValue),
    ITEM_COLLECTION_SET_FLAG(UnkValue),
    ITEM_COLLECTION_CHECK_COMPLETE(UnkValue),
    SELF_STAT_CHANGE_REQUEST(UnkValue),
    CASH_BUFF_EVENT_CANCLE(UnkValue),
    CREATE_PSYCHIC_LOCK(UnkValue),
    RESET_PATH_PSYCHIC_LOCK(UnkValue),
    RELEASE_PSYCHIC_LOCK(UnkValue),
    RESERVE_DAMAGE_PSYCHIC_LOCK(UnkValue),
    CREATE_KINESIS_PSYCHIC_AREA(UnkValue),
    DO_ACTIVE_PSYCHIC_AREA(UnkValue),
    DEBUFF_PSYCHIC_AREA(UnkValue),
    RELEASE_PSYCHIC_AREA(UnkValue),
    PSYCHIC_OVER_REQUEST(UnkValue),
    DEC_PSYCHIC_POINT_REQUEST(UnkValue),
    TOUCH_ME_END_REQUEST(UnkValue),
    BITE_ATTACK_RESPONSE(UnkValue),
    SEND_SAVE_URUS_SKILL(UnkValue),
    GET_SAVED_URUS_SKILL(UnkValue),
    URUS_SHOP_REQUEST(UnkValue),
    URUS_PARTY_MEMBER_LIST(UnkValue),
    USER_KEY_DOWN_STEP_REQUEST(915), // v265.3
    DAILY_GIFT_REQUEST(916), // v265.3
    CYGNUS_SKILL_COMMAND_LOCK(917), // v265.3
    SKILL_COMMAND_LOCK(918), // v265.3
    SKILL_COMMAND_LOCK_ARK(919), // v265.3
    BEAST_FORM_WING_OFF(UnkValue),
    SKILL_COMMAND_LOCK_EVENT(UnkValue),
    RESET_AIR_HIT_COUNT_REQUEST(UnkValue),
    RW_ACTION_CANCEL(UnkValue),
    RELEASE_RW_GRAB(UnkValue),
    RW_CLEAR_CURRENT_ATTACK_REQUEST(UnkValue),
    RW_MULTI_CHARGE_CANCEL_REQUEST(UnkValue),
    FUNTION_FOOTHOLD_MAN(UnkValue),
    DIMENSION_MIRROR_REQUEST(927), // v265.3
    MONSTER_BOOK_MOB_INFO(928), // v265.3
    EXP_POUCH_REQUEST(929), // v265.3
    DEC_STACKING_MATRIX_SKILL_REQUEST(930), // v265.3
    CHARGE_STACKING_MATRIX_SKILL_REQUEST(931), // v265.3
    SHOOT_OBJECT_CREATE_REQUEST(932), // v265.3
    SHOOT_OBJECT_EXPLODE_REQUEST(933), // v265.3
    CHOOSE_LOAD_DICE_NUMBER_REQUEST(UnkValue),
    SHOOT_OBJECT_INCREMENT_REQUEST(938), // v265.3
    SPOTLIGHT_STACK_REQUEST(UnkValue),
    UNION_ASSIGN_REQUEST(951),
    UNION_PRESET_CHANGE(953),
    UNION_PRESET_INFO_REQUEST(954),
    USER_EVENT_GAUGE_GAIN_COIN_REQUEST(UnkValue),
    ACHIEVEMENT_REQUEST(UnkValue),

    INCREASE_SKILL_STACK_REQUEST(UnkValue), // v265.3
    DIVINE_ECHO_EXPIRE_REQUEST(985), // v265.3
    DIMENSIONAL_SWORD_CHANGE(986), // v265.3
    INFERNO_SPHERE_FEATHER_COUNT(988), // v265.3
    STACK_OVER_TIME_SKILL_INCREASE_REQUEST(990), // v265.3
    LARA_STACK_OVER_TIME_SKILL_INCREASE_REQUEST(992), // v265.3
    CREEPING_TOXIN_AREA_REQUEST(993), // v265.3
    BULLET_BLAST_RELOAD_REQUEST(994), // v265.3

    BEAST_TAMER_REGROUP_REQUEST(1012), // v265.3

    DEMONIC_BLAST_KEYDOWN_COST(1013), // v265.3
    PINK_BEAN_MATRYOSHKA_REQUEST(1014), // v265.3
    CLIENT_SYNC_COOLTIME_REQUEST(1157), // v265.3
    V_BLESSING_UPDATE_REQUEST(1016), // v265.3
    AURA_SKILL_UPDATE_REQUEST(1017), // v265.3

    JUPITER_THUNDER_CREATE_REQUEST(1039), // v265.3
    JUPITER_THUNDER_UPDATE_REQUEST(1040), // v265.3
    JUPTIER_THUNDER_UPDATE_RECT_REQUEST(1041), // v265.3
    JUPITER_THUNDER_REMOVE_REQUEST(1042), // v265.3

    FINAL_PACT_REQUEST(1054), // v265.3

    USER_SKILL_ALARM_REQUEST(1084), // v265.3
    MIND_DELVE_REQUEST(1090), // v265.3
    USER_MEDAL_MODIFIED(1099), // v265.3
    USER_TITLE_MODIFIED(1100), // v265.3
    USER_DECORATION_INVENTORY_MODIFIED(1102), // v265.3
    USER_UI_HELPER(1103), // v265.3
    USER_CASH_EQUIPMENT_PRESET_MODIFIED(1114), // v265.3
    USER_EQUIPMENT_PRESET_MODIFIED(1116), // v265.3
    HEXA_SOL_JANUS_REQUEST(1121), // v265.3
    HEXA_MATRIX_OPREATION(1124), // v265.3
    HEXA_ERDA_CONVERSION(1125), // v265.3
    UNION_ARTIFACT_UPDATE_REQUEST(1126), // v265.3
    USER_QUICK_SLOT_MODIFIED(1129), // v265.3
    USER_NODE_STONE_REQUEST(1136), // v265.3
    HEXA_FATE_SHUFFLE_REQUEST(1137), // v265.3
    REN_UNITY_REQUEST(1139), // v265.3
    USER_MEDAL_HONOR_REQUEST(1143), // v265.3
    SWITCH_CHARACTER(1145), // v265.3
    USER_MAPLE_PLANNER_MODIFIED(1146), // v265.3
    USER_EVENT_LIST_OPERATION(1149), // v265.3
    USER_SKILL_USE_REQUEST(1156), // v265.3
    USER_SKILL_CANCEL_REQUEST(1159), // v265.3
    USER_SKILL_PREPARE_STOP(1160), // v265.3
    USER_SKILL_PREPARE_START(1161), // v265.3
    USER_SKILL_MOVING_SHOOT_ATTACK_PREPARE_REQUEST(1162), // v265.3
    USER_SKILL_KEY_DOWN_ATTACK_REQUEST(1163), // v265.3
    USER_OPEN_FAMILIAR_SHOP(1183), // v265.3

    QUICK_PASS_REQUEST(UnkValue),
    GACHAPON_REQUEST(UnkValue),
    FAMILIAR_ADD_REQUEST(UnkValue),
    FAMILIAR_SPAWN_REQUEST(UnkValue),
    FAMILIAR_RENAME_REQUEST(UnkValue),
    GUILD_BBS(UnkValue),
    OPEN_CASH_GACHAPON_REQUEST(UnkValue),
    PAMS_SONG_REQUEST(UnkValue),
    SURPRISE_BOX(UnkValue),
    VIOLET_CUBE_REQUEST(UnkValue),
    USER_SAVE_DAMAGE_SKIN_REQUEST(UnkValue),
    USER_APPLY_DAMAGE_SKIN_REQUEST(UnkValue),
    USER_DELETE_DAMAGE_SKIN_REQUEST(UnkValue),
    FAMILIAR_MOVE(UnkValue),
    FAMILIAR_ATTACK(UnkValue),
    FAMILIAR_SKILL(UnkValue),
    GATHER_REQUEST(UnkValue),

    USER_BEAUTY_DATA_REQUEST(1215),// v265.3

    E_N_D__U_S_E_R(1275), // v265.3
    B_E_G_I_N__F_I_E_L_D(1276), // v265.3

    B_E_G_I_N__L_I_F_E_P_O_O_L(1277), // v265.3
    B_E_G_I_N__M_O_B(1278), // v265.3
    MOB_MOVE(1279), // v265.3
    MOB_APPLY_CTRL(1280), // v265.3
    MOB_DROP_PICK_UP_REQUEST(UnkValue),
    MOB_HIT_BY_OBSTACLE(UnkValue),
    MOB_HIT_BY_OBSTACLE_ATOM(UnkValue),
    MOB_HIT_BY_MOB(UnkValue),
    MOB_SELF_DESTRUCT(UnkValue),
    MOB_SELF_DESTRUCT_COLLISION_GROUP(UnkValue),
    MOB_ATTACK_MOB(UnkValue),
    MOB_SKILL_DELAY_END(UnkValue),
    MOB_TIME_BOMB_END(UnkValue),
    MOB_ESCORT_COLLISION(UnkValue),
    MOB_REQUEST_ESCORT_INFO(UnkValue),
    MOB_ESCORT_STOP_END_REQUEST(UnkValue),
    MOB_AREA_ATTACK_DISEASE(UnkValue),
    MOB_EXPLOSION_START(UnkValue),
    MOB_LIFTING_END(UnkValue),
    MOB_UPDATE_FIXED_MOVE_DIR(UnkValue),
    MOB_CREATE_FIRE_WALK(UnkValue),
    MOB_AFTER_DEAD_REQUEST(UnkValue),
    MOB_DAMAGE_SHARE_INFO(UnkValue),
    MOB_CREATE_AFFECTED_AREA(UnkValue),
    MOB_DOWN_RESPONSE(UnkValue),
    MOB_BLACK_HAND(UnkValue),
    E_N_D__M_O_B(1320), // v265.3

    B_E_G_I_N__N_P_C(1321), // v265.3
    NPC_MOVE(1322), // v265.3
    NPC_SPECIAL_ACTION(1323), // v265.3
    E_N_D__N_P_C(1324), // v265.3

    E_N_D__L_I_F_E_P_O_O_L(1325), // v265.3

    B_E_G_I_N__D_R_O_P_P_O_O_L(1326), // v265.3
    DROP_PICK_UP_REQUEST(1327), // v265.3
    E_N_D__D_R_O_P_P_O_O_L(1328), // v265.3

    B_E_G_I_N__R_E_A_C_T_O_R_P_O_O_L(1329), // v265.3
    REACTOR_HIT(1330), // v265.3
    REACTOR_CLICK(1331), // v265.3
    REACTOR_RECT_IN_MOB(1332), // v265.3
    REACTOR_KEY(1334), // v265.3
    REACTOR_BY_SPACE(1339), // v265.3
    E_N_D__R_E_A_C_T_O_R_P_O_O_L(1340), // v265.3

    B_E_G_I_N__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(UnkValue),
    FISHING_INFO(UnkValue),
    FISHING_END(UnkValue),
    E_N_D__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(UnkValue),

    B_E_G_I_N__P_E_R_S_O_N_A_L__O_B_J_E_C_T(UnkValue),
    DECOMPOSER_REQUEST(UnkValue),
    E_N_D__P_E_R_S_O_N_A_L__O_B_J_E_C_T(UnkValue),

    B_E_G_I_N__E_V_E_N_T__F_I_E_L_D(UnkValue),
    EVENT_START(UnkValue),
    SNOW_BALL_HIT(UnkValue),
    SNOW_BALL_TOUCH(UnkValue),
    COCONUT_HIT(UnkValue),
    TOURNAMENT_MATCH_TABLE(UnkValue),
    PULLEY_HIT(UnkValue),
    E_N_D__E_V_E_N_T__F_I_E_L_D(UnkValue),

    B_E_G_I_N__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(UnkValue),
    M_CARNIVAL_REQUEST(UnkValue),
    E_N_D__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(UnkValue),

    B_E_G_I_N__D_E_F_E_N_S_E__F_I_E_L_D(UnkValue),
    DEFENSE_GAME_REQUEST(UnkValue),
    E_N_D__D_E_F_E_N_S_E__F_I_E_L_D(UnkValue),

    C_O_N_T_I_S_T_A_T_E(UnkValue),
    B_E_G_I_N__P_A_R_T_Y__M_A_T_C_H(UnkValue),
    INVITE_PARTY_MATCH(UnkValue),
    CANCEL_INVITE_PARTY_MATCH(UnkValue),
    PARTY_MEMBER_CANDIDATE_REQUEST(UnkValue),
    URUS_PARTY_MEMBER_CANDIDATE_REQUEST(UnkValue),
    PARTY_CANDIDATE_REQUEST(UnkValue),
    INTRUSION_FRIEND_CANDIDATE_REQUEST(UnkValue),
    INTRUSION_LOBBY_CANDIDATE_REQUEST(UnkValue),
    END_PARTY_MATCH(UnkValue),
    REQUEST_FOOT_HOLD_MOVE(UnkValue),
    GATHER_END_NOTICE(UnkValue),
    ACT_CHANGE_REACTOR_USE_REQUST(UnkValue),
    USER_ANTI_MACRO_BOMB_REQUEST(UnkValue),
    MAKE_ENTER_FIELD_PACKET_FOR_QUICK_MOVE(UnkValue),
    RUNE_STONE_USE_REQ(1383), // v265.3
    RUNE_STONE_SKILL_REQ(1384), // v265.3
    RUNE_STONE_USE_CHK(1385), // v265.3
    OBTACLE_ATOM_COLLISION(UnkValue),
    TIMER_GAUGE_TIMEOUT(UnkValue),
    FALLING_CATCHER_HACK_CHECK(UnkValue),
    COOK_GAME_REQUEST(UnkValue),
    FPS_MODE_EXIT_REQUEST(UnkValue),
    MAKE_ENTER_FIELD_PACKET_FOR_MIRROR_DUNGEON(UnkValue),
    LEAVE_MIRROR_DUNGEON(UnkValue),

    PEACEMAKER_TRAVEL_CONTACT_COUNT(UnkValue),
    PEACEMAKER_EXPLOSION_CONTACT_COUNT(UnkValue),
    ILLIUM_RESONANCE_LINK(UnkValue),

    USER_SECOND_ATOM_COMMAND_REQUEST(1647), // v265.3
    USER_SECOND_ATOM_REMOVE_REQUEST(1648), // v265.3
    USER_SECOND_ATOM_COLLISION_REQUEST(1649), // v265.3

    USER_FARVORITE_MAP_REQUEST(1854), // v265.3
    USER_CASH_CUBE_ITEM_USE_REQUEST(1863), // v265.3
    EXTRA_SYSTEM_REQUEST(1865), // v265.3
    MO_XUAN_STACK_REQUEST(1866), // v265.3
    USER_BUFF_FAVORITE_REQUEST(1906), // v265.3
    USER_SAVE_NAVIGATION_REQUEST(1908), // v265.3
    USER_OPEN_QUICK_MOVE_REQUEST(1909), // v265.3
    USER_FILTER_MAP_OBJECTS_REQUEST(1911), // v265.3
    MAGIC_WHEEL_REQUEST(UnkValue),
    REQUEST_RECEIVE_STUFFS(1939), // v265.3
    COMMERCI_DEPART(UnkValue),

    B_E_G_I_N__R_H_Y_T_H_M_G_A_M_E(UnkValue),
    RHYTHM_GAME_HIT_NOTE(UnkValue),
    RHYTHM_GAME_START_REGION(UnkValue),
    RHYTHM_GAME_END_REGION(UnkValue),
    RHYTHM_GAME_END_SPECIAL_ATTACK(UnkValue),
    RHYTHM_GAME_SELECT_MODE(UnkValue),
    RHYTHM_GAME_ATTACK_REQUEST(UnkValue),
    RHYTHM_GAME_NPC_ACTION_REQUEST(UnkValue),
    RHYTHM_GAME_EXIT_GAME(UnkValue),
    E_N_D__R_H_Y_T_H_M_G_A_M_E(UnkValue),

    B_E_G_I_N__M_O_U_N_T_A_I_N_R_I_D_I_N_G(UnkValue),
    MOUNTAIN_RIDING_HP_INFO(UnkValue),
    MOUNTAIN_RIDING_MOB_INFO(UnkValue),
    E_N_D__M_O_U_N_T_A_I_N_R_I_D_I_N_G(UnkValue),

    B_E_G_I_N__P_I_R_A_N_H_A(UnkValue),
    PIRANHA_INFO(UnkValue),
    PIRANHA_DIE(UnkValue),
    PIRANHA_DAMAGE(UnkValue),
    PIRANHA_PREPARE(UnkValue),
    E_N_D__P_I_R_A_N_H_A(UnkValue),

    B_E_G_I_N__R_O_B_B_I_N_S(UnkValue),
    ROBBINS__INC_BOMB(UnkValue),
    ROBBINS__DEC_BOMB(UnkValue),
    ROBBINS__TOSS_BOMB(UnkValue),
    E_N_D__R_O_B_B_I_N_S(UnkValue),

    B_E_G_I_N__F_A_L_L_I_N_G_S_T_O_N_E(UnkValue),
    FALLING_STONE_INFO(UnkValue),
    FALLING_STONE_HP_INFO(UnkValue),
    FALLING_STONE_PREPARE(UnkValue),
    E_N_D__F_A_L_L_I_N_G_S_T_O_N_E(UnkValue),

    B_E_G_I_N__B_A_T_T_L_E_F_I_E_L_D(UnkValue),
    BATTLE_FIELD_DAMAGE(UnkValue),
    BATTLE_FIELD_SHEEP_REVIVAL_REQ(UnkValue),
    BATTLE_FIELD_SHEEP_REVIVE(UnkValue),
    E_N_D__B_A_T_T_L_E_F_I_E_L_D(UnkValue),

    B_E_G_I_N__B_O_S_S_A_R_E_N_A(UnkValue),
    BOSS_ARENA_SELECT_BOSS(UnkValue),
    BOSS_ARENA_SELECT_SKILL(UnkValue),
    BOSS_ARENA_SELECT_DIFFICULTY(UnkValue),
    BOSS_ARENA_SELECT_CONFIRM(UnkValue),
    E_N_D__B_O_S_S_A_R_E_N_A(UnkValue),

    B_E_G_I_N__C_A_T_A_P_U_L_T(UnkValue),
    CATAPULT__UPGRADE_SKILL(UnkValue),
    E_N_D__C_A_T_A_P_U_L_T(UnkValue),

    FIELD_ATTACK_OBJ_PUSH_ACT(UnkValue),
    FIELD_RESPAWN(UnkValue),

    B_E_G_I_N__S_O_U_L__D_U_N_G_E_O_N(UnkValue),
    SOUL_ITEM_USE(UnkValue),
    SOUL_ITEM_USE_VOTE(UnkValue),
    SOUL_DUNGE_SUMM_SOUL_BOSS(UnkValue),
    E_N_D__S_O_U_L__D_U_N_G_E_O_N(UnkValue),

    B_E_G_I_N__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(UnkValue),
    SPACE_MORABBIT_HIT_EFF(UnkValue),
    SPACE_MORABBIT_DAMAGE(UnkValue),
    E_N_D__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(UnkValue),

    B_E_G_I_N__H_U_N_D_R_E_D_B_I_N_G_O(UnkValue),
    H_BINGO_CHECK_NUMBER(UnkValue),
    H_BINGO_CHECK_BINGO(UnkValue),
    E_N_D__H_U_N_D_R_E_D_B_I_N_G_O(UnkValue),

    B_E_G_I_N__T_Y_P_I_N_G_G_A_M_E(UnkValue),
    TYPING_GAME_CHECK_MSG(UnkValue),
    TYPING_GAME_WORD_MOB_ATTACK(UnkValue),
    TYPING_GAME_LEVEL_SELECT(UnkValue),
    TYPING_GAME_SKILL_ATTACK(UnkValue),
    TYPING_GAME_FIELD_OUT(UnkValue),
    E_N_D__T_Y_P_I_N_G_G_A_M_E(UnkValue),

    B_E_G_I_N__H_U_N_D_R_E_D_O_X_Q_UI_Z(UnkValue),
    H_OX_QUIZ_SELECTED(UnkValue),
    E_N_D__H_U_N_D_R_E_D_O_X_Q_UI_Z(UnkValue),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T_R_P_S(UnkValue),
    S_P_RPS_GAME_USER_SELECT(UnkValue),
    S_P_RPS_GAME_ANSWER(UnkValue),
    S_P_RPS_GAME_LEAVE(UnkValue),
    E_N_D__S_T_A_R_P_L_A_N_E_T_R_P_S(UnkValue),

    B_E_G_I_N__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(UnkValue),
    SSFS_HIT_USER(UnkValue),
    SSFS_LETHAL_ATTACK(UnkValue),
    SSFS_EXIT(UnkValue),
    E_N_D__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(UnkValue),

    B_E_G_I_N__F_I_E_L_D_S_T_A_T_E(UnkValue),
    STAR_PLANET__H_BINGO_CHECK_NUMBER(UnkValue),
    STAR_PLANET__H_BINGO_CHECK_BINGO(UnkValue),
    STAR_PLANET__H_BINGO_SEND_NUMBER(UnkValue),
    STAR_PLANET__H_RPS_SELECTED(UnkValue),
    STAR_PLANET__GROUP_DANCE_SELECTED(UnkValue),
    STAR_PLANET__GROUP_DANCE_CANCEL(UnkValue),
    E_N_D__F_I_E_L_D_S_T_A_T_E(UnkValue),

    B_E_G_I_N__M_O_M_E_N_T_S_W_I_M_A_R_E_A(UnkValue),
    MOMENT_SWIM_AREA__WATER_LEVEL(UnkValue),
    E_N_D__M_O_M_E_N_T_S_W_I_M_A_R_E_A(UnkValue),

    B_E_G_I_N__G_H_O_S_T_P_A_R_K(UnkValue),
    GHOST_PARK_USE_RUNE_REQ(UnkValue),
    GHOST_PARK_RUNE_HEAL_REQ(UnkValue),
    GHOST_PARK_HIT_BULLET(UnkValue),
    E_N_D__G_H_O_S_T_P_A_R_K(UnkValue),

    B_E_G_I_N__F_I_E_L_D__U_R_U_S(UnkValue),
    URUS_SAVE_DEADLY_USER(UnkValue),
    E_N_D__F_I_E_L_D__U_R_U_S(UnkValue),

    FIELD_SKILL_USE_REQUEST(UnkValue),
    FIELD_WEATHER__MSG(UnkValue),
    FIELD_STAT_Q_R_EX_DAY(UnkValue),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(UnkValue),
    POLO_FRITO_BOUNTY_HUNTING_REQUEST(UnkValue),
    E_N_D__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(UnkValue),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(UnkValue),
    POLO_FRITO_TOWN_DEFENSE_REQUEST(UnkValue),
    E_N_D__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(UnkValue),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(UnkValue),
    POLO_FRITO_COURTSHIP_DANCE_RESULT(UnkValue),
    E_N_D__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(UnkValue),

    B_E_G_I_N__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(UnkValue),
    DEMIAN_OBJECT_MAKE_ENTER_ACK(UnkValue),
    DEMIAN_OBJECT_NODE_END(UnkValue),
    DEMIAN_OBJECT_ERR__RECREATE(UnkValue),
    E_N_D__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(UnkValue),

    B_E_G_I_N__B_O_S_S__L_U_C_I_D(UnkValue),
    LUCID_FAIRY_DUST_CHECK(UnkValue),
    LUCID_ACTIVATE_STATUE_REQUEST(UnkValue),
    LUCIDE_WELCOME_BARRAGE_END(UnkValue),
    E_N_D__B_O_S_S__L_U_C_I_D(UnkValue),

    B_E_G_I_N__B_O_S_S__W_I_L_L(UnkValue),
    WILL_USE_MOON_GAUGE(UnkValue),
    WILL_BEHOLDER_EYES_HIT(UnkValue),
    WILL_SPIDER_WEB_HIT(UnkValue),
    E_N_D__B_O_S_S__W_I_L_L(UnkValue),

    B_E_G_I_N__B_O_S_S__G_O_L_L_U_X(UnkValue),
    GOLLUX_UNK_REQUEST(UnkValue),
    GOLLUX_UNK2_REQUEST(UnkValue),
    GOLLUX_UNK3_REQUEST(UnkValue),
    GOLLUX_OUT_REQUEST(UnkValue),
    E_N_D__B_O_S_S__G_O_L_L_U_X(UnkValue),

    E_N_D__F_I_E_L_D(UnkValue),

    CHECK_S_P_W_CREATE_NEW_CHARACTER(UnkValue),
    SET_S_P_W(UnkValue),

    B_E_G_I_N__C_A_S_H_S_H_O_P(1813), // v265.3
    CASH_SHOP_QUERY_CASH_REQUEST(1814), // v265.3
    CASH_SHOP_CASH_ITEM_REQUEST(1815), // v265.3
    CASH_SHOP_CHECK_COUPON_REQUEST(UnkValue),
    CASH_SHOP_MEMBER_SHOP_REQUEST(UnkValue),
    CASH_SHOP_GIFT_MATE_INFO_REQUEST(UnkValue),
    CASH_SHOP_SEARCH_LOG(UnkValue),
    CASH_SHOP_SAVE_AVATAR_REQUEST(UnkValue),
    CASH_SHOP_USE_REWARD_POINT(UnkValue),
    CASH_SHOP_COODINATION_REQUEST(UnkValue),
    CASH_SHOP_CHECK_MILEAGE_REQUEST(UnkValue),
    CASH_SHOP_NAVER_USAGE_INFO_REQUEST(UnkValue),
    M_V_P__DAILY_PACK__REQUEST(UnkValue),
    M_V_P__SPECIAL_PACK__REQUEST(UnkValue),
    CASH_SHOP_RECEIVE_FREE_GIFT(UnkValue),
    CASH_SHOP_ACTION(UnkValue),
    CASH_SHOP_BUY_EQUIPPED_ITEM(UnkValue),
    E_N_D__C_A_S_H_S_H_O_P(UnkValue),

    B_E_G_I_N__R_A_I_S_E(UnkValue),
    RAISE_REFESH(UnkValue),
    RAISE_UI_STATE(UnkValue),
    RAISE_INC_EXP(UnkValue),
    RAISE_ADD_PIECE(UnkValue),
    E_N_D__R_A_I_S_E(UnkValue),

    SEND_MATE_MAIL(UnkValue),
    REQUEST_GUILD_BOARD_AUTH_KEY(UnkValue),
    REQUEST_CONSULT_AUTH_KEY(UnkValue),
    REQUEST_CLASS_COMPETION_AUTH_KEY(UnkValue),
    REQUEST_WEB_BOARD_AUTH_KEY(UnkValue),
    IRBOX_EVENT(UnkValue),
    ELODIN_SMALL_BOTTLE_CHECK(UnkValue),
    ELODIN_SMALL_BOTTLE_SETUP( UnkValue),
    ELODIN_PURE_WATER(UnkValue),

    B_E_G_I_N__I_T_E_M_U_P_G_R_A_D_E(UnkValue),
    GOLD_HAMMER_REQUEST(UnkValue),
    GOLD_HAMMER_COMPLETE(UnkValue),
    E_N_D__I_T_E_M_U_P_G_R_A_D_E(UnkValue),

    B_E_G_I_N__B_A_T_T_L_E_R_E_C_O_R_D(1849), // v265.3
    BATTLE_RECORD_ON_OFF_REQUEST(1850), // v265.3
    BATTLE_RECORD_SKILL_DAMAGE_LOG(1851), // v265.3
    E_N_D__B_A_T_T_L_E_R_E_C_O_R_D(1852), // v265.3

    REQUEST_STATUS_CHECK(1860), // v265.3
    CLIENT_HEARTBEAT(1930), // v265.3
    USER_SKIP_TERA_BLINK(1935), // v265.3

    NO(4000),
    ;

    private final static Map<Short, InHeader> opToHeaderMap = new HashMap<>();
    private static final List<InHeader> spam = Arrays.asList(
            LOGIN_INIT_CHECK,
            CLIENT_HEARTBEAT,
            UPDATE_CLIENT_ENVIRONMENT,
            PONG,
            WVS_SET_UP_STEP,
            SECURITY_PACKET,
            PRIVATE_SERVER_PACKET,
            MOB_MOVE,
            USER_MOVE,
            PASSIVESKILL_INFO_UPDATE,
            USER_DOT_HEAL,
            USER_CHANGE_STAT_REQUEST,
            SUMMONED_MOVE,
            USER_CALC_DAMAGE_STAT_SET_REQUEST,
            MOB_APPLY_CTRL,
            USER_REQUEST_INSTANCE_TABLE,
            USER_QUEST_REQUEST,
            CHECK_LOGIN_AUTH_INFO,
            CHECK_SPW_REQUEST,
            NPC_MOVE,
            FAMILIAR_MOVE,
            PET_MOVE,
            FOX_MAN_MOVE,
            SKILL_PET_MOVE,
            SKILL_PET_ACTION,
            AUTH_HEARTBEAT,
            OBTACLE_ATOM_COLLISION,
            ANDROID_MOVE,
            DRAGON_MOVE,
            USER_HIT,
            USER_EMOTION,
            USER_B2_BODY_REQUEST,
            USER_PINKBEAN_YO_YO_STACK_REQUEST,
            USER_CHARGE_WIND_ENERGY_REQUEST,
            DEC_PSYCHIC_POINT_REQUEST,
            SHOOT_OBJECT_INCREMENT_REQUEST,
            EGO_EQUIP_CREATE_UPGRADE_ITEM_COST_REQUEST,
            USER_CLIENT_RESOLUTION_REQUEST,
            USER_ACTIVATE_DAMAGE_SKIN,
            USER_ACTIVATE_DAMAGE_SKIN_PREMIUM,
            CASH_SHOP_BUY_EQUIPPED_ITEM,
            USER_CHECK_TEMPORARY_STAT_DURATION_REQUEST,
            POLO_FRITO_BOUNTY_HUNTING_REQUEST,
            POLO_FRITO_TOWN_DEFENSE_REQUEST,
            EXCEPTION_LOG,
            EXCEPTION_LOG_2
    );

    static {
        for (InHeader ih : values()) {
            opToHeaderMap.put(ih.getValue(), ih);
        }
    }

    private short value;

    InHeader(int op) {
        this.value = (short) op;
    }

    public static InHeader getInHeaderByOp(int op) {
        return opToHeaderMap.getOrDefault((short) op, null);
    }

    public static boolean isSpamHeader(InHeader inHeaderByOp) {
        return spam.contains(inHeaderByOp);
    }

    public short getValue() {
        return value;
    }
}
