package net.swordie.ms.client.character.skills.temp;

import java.util.*;

public enum CharacterTemporaryStat implements Comparator<CharacterTemporaryStat> {
    IndiePAD(0),
    IndieMAD(1),
    IndiePDD(2),
    IndieMHP(3),
    IndieMHPR(4),
    IndieMMP(5),
    IndieMMPR(6),
    IndieACC(7),
    IndieEVA(8),
    IndieJump(9),
    IndieSpeed(10),
    IndieAllStat(11),
    IndieStatRBasic(12),
    IndieDodgeCriticalTime(13),
    IndieEXP(14),
    IndieBooster(15),
    IndieFixedDamageR(16),
    PyramidStunBuff(17), // Osiris' Eye: Stuns monsters for 1 second. Includes Pharaoh Yetis and Pharaoh Mummies at a 30% chance. Costs 500 points.
    PyramidFrozenBuff(18), // Horus' Eye: Slows down all monsters for 15 seconds. Includes Pharaoh Yetis and Pharaoh Mummies at a 30% chance. Costs 700 points.
    PyramidFireBuff(19), // Isis' Eye: Does Damage over time to all monsters for 15 seconds every second. Costs 500 points.
    PyramidBonusDamageBuff(20), // Anubis' Eye: Increases 40 attack for 15 seconds. Costs 500 points.
    IndieRelaxEXP(21),
    IndieSTR(22),
    IndieDEX(23),
    IndieINT(24),
    IndieLUK(25),
    IndieDamR(26),
    IndieScriptBuff(27),
    IndieMDF(28),
    IndieAsrR(29),
    IndieTerR(30),
    IndieCrR(31),
    IndiePDDR(32),
    IndieCD(33),
    IndieCDPer(34),
    IndieBDR(35),
    IndieStatR(36),
    IndieStance(37),
    IndieIgnoreMobpdpR(38),
    IndieEmpty(39),
    IndiePADR(40),
    IndieMADR(41),
    IndieEVAR(42),
    IndieDrainHP(43),
    IndiePMdR(44),
    IndieForceJump(45),
    IndieForceSpeed(46),
    IndieQrPointTerm(47),
    IndieLoopEffect(48),
    IndiePeriodicalSkillActivation(49),
    IndieEventForSkill(50),
    IndieItemDropRate(51),
    IndieBuffIcon(52),
    IndieCooltimeReduce(53),
    IndieNotDamaged(54),
    IndieKeyDownTime(55),
    IndieDamReduceR(56),
    IndieSpecificSkill(57),
    IndieEVARReduceR(58),
    IndieHitDamR(59),
    IndieApplySuperStance(60),
    IndieFlyAcc(61),
    IndieAllHitDamR(62),
    IndieArc(63),
    IndieAut(64),
    IndiePowerGuard(65),
    IndieDropPer(66),
    IndieMesoAmountRate(67),
    IndieCheckTimeByClient(68),
    IndieDotHealHP(69),
    IndieDotHealMP(70),
    IndieNormalDamReduceR(71),
    IndieIgnorePCounter(72),
    IndieBarrier(73),
    IndieStarForce(74),
    IndieNBDR(75),
    IndieMonsterCollectionR(76),
    IndieMPConReduceR(77),
    IndieAntiMagicShell(78),
    IndieDecDamTargetMob(79),
    IndieFinalDamRBuffIcon(80),
    IndiePMdRExtra(81),
    IndieAllSkill(82),
    IndiePartyExpRate(83),
    IndieCrMin(84),
    IndieWaterSmashBuff(85),
    IndieCharColor(86),
    IndieStatCount(87),
    // End of Indie stats
    PAD(88),
    PDD(89),
    MAD(90),
    ACC(91),
    EVA(92),
    Craft(93),
    Speed(94),
    Jump(95),
    MagicGuard(96),
    DarkSight(97),
    Booster(98),
    PowerGuard(99),
    MaxHP(100),
    MaxMP(101),
    Invincible(102),
    SoulArrow(103),
    Stun(104),
    Poison(105),
    Seal(106),
    Darkness(107),
    ComboCounter(108),
    BlessedHammer(109),
    BlessedHammerActive(110),
    WeaponCharge(111),
    HolySymbol(112),
    MesoUp(113),
    ShadowPartner(114),
    ThiefSteal(115),
    PickPocket(116),
    BloodyExplosion(117),
    Thaw(118),
    Weakness(119),
    Curse(120),
    Slow(121),
    Morph(122),
    Regen(123),
    BasicStatUp(124),
    Stance(125),
    SharpEyes(126),
    ManaReflection(127),
    Attract(128),
    NoBulletConsume(129),
    Infinity(130),
    AdvancedBless(131),
    IllusionStep(132),
    Blind(133),
    Concentration(134),
    BanMap(135),
    MaxLevelBuff(136),
    MesoUpByItem(137),
    MesoAmountRate(138),
    MesoAmountRateRune(139),
    Ghost(140),
    Barrier(141),
    ReverseInput(142),
    ItemUpByItem(143),
    RespectPImmune(144),
    RespectMImmune(145),
    DefenseAtt(146),
    DefenseState(147),
    DojangBerserk(148),
    DojangInvincible(149),
    DojangShield(150),
    SoulMasterFinal(151),
    WindBreakerFinal(152),
    Mortality(153),
    KarmaBlade(154),
    ElementalReset(155),
    HideAttack(156),
    EventRate(157),
    ComboAbilityBuff(158),
    ComboDrain(159),
    RepeatEffect(160),
    ExpBuffRate(161),
    StopPortion(162),
    StopMotion(163),
    Fear(164),
    HiddenPieceOn(165),
    MagicShield(166),
    MagicResistance(167),
    SoulStone(168),
    Flying(169),
    Frozen(170),
    AssistCharge(171),
    Enrage(172),
    DrawBack(173),
    NotDamaged(174),
    FinalCut(175),
    HowlingAttackDamage(176),
    BeastForm(177),
    Dance(178),
    EMHP(179),
    EMMP(180),
    EPAD(181),
    EMAD(182),
    EPDD(183),
    Guard(184),
    RidingExpireInfoSave(185),
    NextSpecificSkillDamageUp(186),
    GravityConstraint(187),
    PinkbeanMinibeenMove(188),
    Sneak(189),
    Mechanic(190),
    BeastFormMaxHP(191),
    Dice(192),
    BlessingArmor(193),
    DamR(194),
    TeleportMasteryOn(195),
    CombatOrders(196),
    Beholder(197),
    DispelItemOption(198),
    Inflation(199),
    OnixDivineProtection(200),
    Web(201),
    Bless(202),
    TimeBomb(203),
    DisOrder(204),
    Thread(205),
    Team(206),
    Explosion(207),
    BuffLimit(208),
    STR(209),
    INT(210),
    DEX(211),
    LUK(212),
    DispelItemOptionByField(213),
    DarkTornado(214),
    PVPDamage(215),
    PvPScoreBonus(216),
    PvPInvincible(217),
    PvPRaceEffect(218),
    WeaknessMdamage(219),
    Frozen2(220),
    PVPDamageSkill(221),
    AmplifyDamage(222),
    Shock(223),
    InfinityForce(224),
    IncMaxHP(225),
    IncMaxMP(226),
    HolyMagicShell(227),
    KeyDownTimeIgnore(228),
    ArcaneAim(229),
    MasterMagicOn(230),
    AsrR(231),
    TerR(232),
    DamAbsorbShield(233),
    DevilishPower(234),
    Anemoi(235),
    Roulette(236),
    RouletteStack(237),
    SpiritLink(238),
    AsrRByItem(239),
    Event(240),
    CriticalBuff(241),
    DropRate(242),
    PlusExpRate(243),
    ItemInvincible(244),
    Awake(245),
    ItemCritical(246),
    ItemEvade(247),
    Event2(248),
    VampiricTouch(249),
    DDR(250),
    IncTerR(251),
    IncAsrR(252),
    DeathMark(253),
    UsefulAdvancedBless(254),
    Lapidification(255),
    VenomSnake(256),
    CarnivalAttack(257),
    CarnivalDefence(258),
    CarnivalExp(259),
    SlowAttack(260),
    PyramidEffect(261),
    HollowPointBullet(262),
    KeyDownMoving(263),
    IgnoreTargetDEF(264),
    StrikerElectricUsed(265),
    StrikerElectricStack(266),
    ReviveOnce(267),
    Invisible(268),
    EnrageCr(269),
    EnrageCrDamMin(270),
    Judgement(271),
    DojangLuckyBonus(272),
    PainMark(273),
    Magnet(274),
    MagnetArea(275),
    GuidedArrow(276),
    StraightForceAtomTargets(277),
    LefBuffMastery(278),
    TempSecondaryStat(279),
    CoalitionSupportSoldierStorm(280),
    LefMageLinkSkill(281),
    SixthJavelinStack(282),
    SixthGloryWingJavelinStack(283),
    SixthCrystalStack(284),
    ShadowMomentum(285),
    GrandCross(286),
    YetiCook(287),
    PinkbeanCheer(288),
    DropPer(289),
    VampDeath(290),
    BlessingArmorIncPAD(291),
    KeyDownAreaMoving(292),
    Larkness(293),
    StackBuff(294),
    AntiMagicShell(295),
    LifeTidal(296),
    HitCriDamR(297),
    SmashStack(298),
    PartyBarrier(299),
    ReshuffleSwitch(300),
    SpecialAction(301),
    VampDeathSummon(302),
    StopForceAtomInfo(303),
    SoulGazeCriDamR(304),
    SoulRageCount(305),
    PowerTransferGauge(306),
    AffinitySlug(307),
    Trinity(308),
    IncMaxDamage(309),
    BossShield(310),
    MobZoneState(311),
    GiveMeHeal(312),
    TouchMe(313),
    Contagion(314),
    SoulExalt(315),
    IgnoreAllCounter(316),
    IgnorePImmune(317),
    IgnoreAllImmune(318),
    IgnoreAllAbout(319),
    FinalJudgement(320),
    FireAura(321),
    VengeanceOfAngel(322),
    HeavensDoor(323),
    Preparation(324),
    BullsEye(325),
    IncEffectHPPotion(326),
    IncEffectMPPotion(327),
    BleedingToxin(328),
    IgnoreMobDamR(329),
    Asura(330),
    MegaSmasher(331),
    FlipTheCoin(332),
    UnityOfPower(333),
    Stimulate(334),
    ReturnTeleport(335),
    DropRIncrease(336),
    IgnoreMobpdpR(337),
    BdR(338),
    CapDebuff(339),
    Exceed(340),
    DiabolikRecovery(341),
    SurpassLimit(342),
    FinalAttackProp(343),
    ExceedOverload(344),
    OverloadCount(345),
    BuckShot(346),
    FireBomb(347),
    HalfstatByDebuff(348),
    SurplusSupply(349),
    SetBaseDamage(350),
    EVAR(351),
    NewFlying(352),
    AmaranthGenerator(353),
    CygnusElementSkill(354),
    StrikerHyperElectric(355),
    EventPointAbsorb(356),
    EventAssemble(357),
    StormBringer(358),
    ACCR(359),
    DEXR(360),
    Translucence(361),
    PoseType(362),
    CosmicForge(363),
    ElementSoul(364),
    CosmicOrb(365),
    GlimmeringTime(366),
    TrueSight(367),
    SoulExplosion(368),
    SoulMP(369),
    FullSoulMP(370),
    SoulSkillDamageUp(371),
    ElementalCharge(372),
    Restoration(373),
    CrossOverChain(374),
    Reincarnation(375),
    ReincarnationMission(376),
    ReincarnationOnOff(377),
    ChillingStep(378),
    DotBasedBuff(379),
    SixthDotBasedBuff(380),
    BlessEnsenble(381),
    ComboCostInc(382),
    NaviFlying(383),
    Holding(384),
    QuiverCatridge(385),
    ExtraQuiverCatridge(386),
    ExtraQuiverMagic(387),
    ExtraQuiverVamp(388),
    UserControlMob(389),
    ImmuneBarrier(390),
    CriticalGrowing(391),
    LastUseSkillAttr(392),
    QuickDraw(393),
    BowMasterConcentration(394),
    ElementFlameBuff(395),
    TimeFastABuff(396),
    TimeFastBBuff(397),
    InfiniteResonance(398),
    GatherDropR(399),
    AimBox2D(400),
    CursorSniping(401),
    DebuffTolerance(402),
    TearsOfFairy(403),
    DotHealHPPerSecond(404),
    DotHealMPPerSecond(405),
    SpiritGuard(406),
    EunwolUnleashFoxOrb(407),
    PreReviveOnce(408),
    SetBaseDamageByBuff(409),
    LimitMP(410),
    ReflectDamR(411),
    ComboTempest(412),
    MHPCutR(413),
    MMPCutR(414),
    SelfWeakness(415),
    ElementDarkness(416),
    FlareTrick(417),
    FlameDischarge(418),
    Dominion(419),
    SiphonVitality(420),
    DarknessAscension(421),
    BossWaitingLinesBuff(422),
    DamageReduce(423),
    ShadowServant(424),
    ShadowIllusion(425),
    KnockBack(426),
    AddAttackCount(427),
    ComplusionSlant(428),
    JaguarSummoned(429),
    JaguarCount(430),
    SSFShootingAttack(431),
    DevilCry(432),
    ShieldAttack(433),
    DarkLighting(434),
    AttackCountX(435),
    BMageDeath(436),
    BombTime(437),
    NoDebuff(438),
    BattlePvP_Mike_Shield(439),
    BattlePvP_Mike_Bugle(440),
    XenonAegisSystem(441),
    AngelicBursterSoulSeeker(442),
    EunwolFoxSpirit(443),
    NightWalkerBat(444),
    NightLordMark(445),
    WizardIgnite(446),
    FireBarrier(447),
    ChangeFoxMan(448),
    PairingUser(449),
    Frenzy(450),
    ShadowSpear(451),
    MastemaGuard(452),
    Elysion(453),
    QuiverFullBurst(454),
    SwordBaptism(455),
    WildGrenade(456),
    WildGrenadeSpark(457),
    ChainMantisADV(458),
    FieldGimmickFear(459),
    ImmuneStun(460),
    BattlePvP_Helena_Mark(461),
    BattlePvP_Darklord_Explosion(462),
    BattlePvP_Helena_WindSpirit(463),
    BattlePvP_LangE_Protection(464),
    BattlePvP_LeeMalNyun_ScaleUp(465),
    BattlePvP_Revive(466),
    PinkbeanAttackBuff(467),
    PinkbeanRelax(468),
    PinkbeanRollingGrade(469),
    PinkbeanYoYoStack(470),
    RandAreaAttack(471),
    RandAreaAttack2(472),
    ShineRuneAttack(473),
    NextAttackEnhance(474),
    PirateDesire(475),
    AranCombotempastOption(476),
    ViperTimeLeap(477),
    RoyalGuardState(478),
    BodyRectGuardPrepare(479),
    MichaelSoulLink(480),
    MichaelStanceLink(481),
    TriflingWhimOnOff(482),
    AddRangeOnOff(483),
    KinesisPsychicPoint(484),
    KinesisPsychicOver(485),
    KinesisIncMastery(486),
    KinesisPsychicEnergeShield(487),
    BladeStance(488),
    DebuffActiveSkillHPCon(489),
    DebuffIncHP(490),
    BowMasterMortalBlow(491),
    AngelicBursterSoulResonance(492),
    Fever(493),
    RpSiksin(494),
    TeleportMasteryRange(495),
    FixCoolTime(496),
    IncMobRateDummy(497),
    AdrenalinBoost(498),
    AranDrain(499),
    AranBoostEndHunt(500),
    RWCylinder(501),
    RWCombination(502),
    RWVulkanPunch(503),
    RWMagnumBlow(504),
    RWBarrier(505),
    RWBarrierHeal(506),
    RWMaximizeCannon(507),
    RWOverHeat(508),
    UsingScouter(509),
    RWMovingEvar(510),
    Stigma(511),
    EunwolSoulSeperateNotTime(512),
    HeavensDoorNotTime(513),
    RuneStoneNoTime(514),
    XenonRocketRunch(515),
    TransformOverMan(516),
    EnergyBust(517),
    LightningUnion(518),
    BulletParty(519),
    LoadedDice(520),
    BishopPray(521),
    ChainArtsFury(522),
    MichaelFixDamDecTime(523),
    PinkbeanYoYoAddDamR(524),
    Warrior_AuraWeapon(525),
    Warrior_AuraWeaponStack(526),
    Wizard_OverloadMana(527),
    Michael_RhoAias(528),
    Kinesis_DustTornado(529),
    NightLord_SpreadThrow(530),
    HowlingGaleStack(531),
    CannonShooter_BFCannonBall(532),
    CannonShooter_MiniCannonBall(533),
    CannonShooter_RollingCannon(534),
    Shadower_ShadowAssault(535),
    CreateEventMeso(536),
    MesoRanger_MesoDizerX(537),
    CoronaBuffOverlap(538),
    FifthAdvWarriorShield(539),
    SplitArrow(540),
    FreudBlessing(541),
    OverloadMode(542),
    FifthSpotLight(543),
    OutSide(544),
    WeaponVariety(545),
    LefGloryWing(546),
    Shadower_Assassination(547),
    ConvertAD(548),
    EtherealForm(549),
    ReadyToDie(550),
    Oblivion(551),
    Cr2CriDamR(552),
    BlackMageCreate(553),
    BlackMageDestroy(554),
    BlackMageMonochrome(555),
    HitStackDamR(556),
    BuffControlDebuff(557),
    DispersionDamage(558),
    HarmonyLink(559),
    LefFastCharge(560),
    BuffIconNoShadow(561),
    CrystalChargeBuffIcon(562),
    LioMachinaCombineBuffIcon(563),
    CoalitionSupportWarplaneBuffIcon(564),
    BattlePvP_Ryude_Frozen(565),
    BattlePvP_Ryude_Buff(566),
    AntiMagicShellByJewelMaking(567),
    DamageRateSetUpForApc(568),
    SpecterGauge(569),
    SpecterMode(570),
    SpellBullet_Plain(571),
    SpellBullet_Scarlet(572),
    SpellBullet_Gust(573),
    SpellBullet_Abyss(574),
    ComingDeath(575),
    GreatOldAbyss(576),
    SixthPhoenix(577),
    HolyAdvent(578),
    ZodiacBurst(579),
    CombatFrenzy(580),
    LPSpellAmplification(581),
    LPInfinitySpell(582),
    LPMagicCircuitFullDrive(583),
    LPBattleMode(584),
    LPHoldSpecterGauge(585),
    DiscoveryWeather(586),
    BossWill_Infection(587),
    PvpApcTeam(588),
    BigBangAttackCharge(589),
    HolyMagicShellReUse(590),
    StrikerComboStack(591),
    HeroComboInstinct(592),
    HeroAuraBladeStack(593),
    HeroAuraBladeAdv(594),
    HeroSongOfBlade(595),
    KhaliUltimatum(596),
    WindBreakerStormGuard(597),
    FlameWizardInfiniteFlame(598),
    MichaelSwordOfLight(599),
    PhantomMarkOfPhantomOwner(600),
    PhantomMarkOfPhantomTarget(601),
    RescuedSoldierBuffIcon1(602),
    RescuedSoldierBuffIcon2(603),
    FireBirdSupport(604),
    FireBirdSupportActive(605),
    AuraOfLife(606),
    MemoryOfJourney(607),
    DecBaseDamageDebuff(608),
    LimitConsumeDebuff(609),
    LimitEquipStatDebuff(610),
    BlackMageWeaponDestruction(611),
    BlackMageWeaponCreation(612),
    DestinyWeaponIndomitable(613),
    DestinyWeaponDecisive(614),
    BattlePvP_LangE_LiverStack(615),
    BattlePvP_Mike_Amor(616),
    SiphonVitalityBarrier(617),
    PathFinderAncientGuidance(618),
    BattlePvP_KeyDown(619),
    BattlePvP_Wongki_FlyingCharge(620),
    BattlePvP_Wongki_AwesomeFairy(621),
    BattlePvP_Mugong_PandaZone(622),
    BattleSurvivalDefence(623),
    BattleSurvivalInvincible(624),
    EventPvPDefence(625),
    EventPvPInvincible(626),
    EventSoccerBall(627),
    EventSoccerMomentBuff(628),
    ZeroDamageDebuff(629),
    FifthGoddessBless(630),
    CommonItemSkillContinuous(631),
    PinkbeanMatryoshka(632),
    NewtroWarriors(633),
    SilverMane(634),
    SilverManeBuff(635),
    BattlePVPAttBuff(636),
    MinigameStat(637),
    LuckyPapylus(638),
    AnimaThiefTaoistType(639),
    AnimaThiefTaoistGauge(640),
    AnimaThiefCloneAttack(641),
    AnimaThiefFifthCloneAttack(642),
    AnimaThiefButterfly(643),
    MiracleDrug(644),
    MiracleDrugNoCon(645),
    AnimaThiefMetaphysics(646),
    NoviceMagicianLink(647),
    NerotaPower(648),
    ChampionDoubleUp(649),
    LibraryMissionGuard(650),
    XenonHoloGramGraffiti(651),
    KeyDownEnable(652),
    DracoSlasherNoCooltime(653),
    WillOfSword(654),
    LWSwordGauge(655),
    LWCreation(656),
    LWDike(657),
    LWWonder(658),
    LWRestore(659),
    LefWarriorNobility(660),
    LWResonanceBuff(661),
    RunePurification(662),
    RuneContagion(663),
    DebuffHallucination(664),
    BMageAuraYellow(665),
    BMageAuraDrain(666),
    BMageAuraBlue(667),
    BMageAuraDark(668),
    BMageAuraDebuff(669),
    BMageAuraUnion(670),
    IceAura(671),
    KnightsAura(672),
    ZeroAuraStr(673),
    NovaArcherIncanation(674),
    AnimaThiefMetaphysicsBuff(675),
    RevenantGauge(676),
    DeathDance(677),
    ShadowShield(678),
    AranComboTempestAura(679),
    XenonBursterLaser(680),
    BMageAbyssalLightning(681),
    StrikerThunderChain(682),
    MercedesRoyalKnight(683),
    PhantomDefyingFate(684),
    FWSalamanderMischiefAttack(685),
    KinesisLawOfGravity(686),
    RepeatinCartrige(687),
    LefMageCrystalGate(688),
    ThrowBlasting(689),
    AnimaThiefIllusion(690),
    DarknessAura(691),
    WeaponVarietyFinale(692),
    Equinox(693),
    EquinoxActive(694),
    ZeroEgoWeaponAlpha(695),
    RelicUnboundD(696),
    RWAfterImage(697),
    NADragonGauge(698),
    NADragonEnchant(699),
    NADeathBlessing(700),
    NAThanatosDescent(701),
    NAAnnihilation(702),
    NARemainIncense(703),
    NAOminousStream(704),
    NABrutalPang(705),
    MobFlashBang(706),
    IgnorePriestDispel(707),
    LimitRecovery(708),
    NALinkSkill(709),
    StrikerChainReaction(710),
    LimitHealFactor(711),
    AdminCritical(712),
    AdminCriticalDam(713),
    AdminIgnoreTargetDEF(714),
    AdminBDR(715),
    AdminBuffTimeR(716),
    AdminActionSpeed(717),
    AdrenalinActivate(718),
    ATScrollPassive(719),
    YetiFuryGauge(720),
    YetiFuryMode(721),
    YetiMushroom(722),
    YetiMyFriendPepe(723),
    PinkbeanShowTime(724),
    DecFinalDamageDebuff(725),
    AMEarthVeinOnOff(726),
    AMPlanting(727),
    AMStoneShield(728),
    AMAbsorptionRiver(729),
    AMAbsorptionWind(730),
    AMAbsorptionSun(731),
    AMArtificialEarthVein(732),
    IgnoreFrictionOnOff(733),
    AnimaLotus(734),
    AMLinkSkill(735),
    AMEVTeleport(736),
    BossFieldFinalDamR(737),
    StormWhim(738),
    SeaSerpent(739),
    SerpentStone(740),
    SerpentScrew(741),
    Leviathan(742),
    FlameSweep(743),
    Cosmos(744),
    EnhancePiercing(745),
    EnhanceSniping(746),
    UltimateSniping(747),
    UltimatePiercing(748),
    EnhanceQuadrupleThrow(749),
    EnhanceHeadShot(750),
    UnwearyingRun(751),
    CrusaderPanic(752),
    IceAuraZone(753),
    HolyWater(754),
    EpicDungeonGauge(755),
    EpicDungeonMiddleBossBarrier(756),
    TriumphFeather(757),
    SixthAngelsRay(758),
    GrandFinale(759),
    WarInTheShade(760),
    FlashMirage(761),
    HolyBlood(762),
    OrbitalExplosion(763),
    DragonSlave(764),
    LimitBreakFinalAttack(765),
    TranscendentLight(766),
    SixthAssassination(767),
    SixthAssassinationDarkSight(768),
    SixthCovertShadowBuff(769),
    ArtificialEvolution(770),
    SixthFrozenLightning(771),
    KinesisUltimateBPM(772),
    ElementalKnight(773),
    LarknessStop(774),
    SummonChakri(775),
    SixthResonate(776),
    EnhanceNightLordFourSeasons(777),
    DarknessShuriken(778),
    ShadowAcceleration(779),
    ShadowBurst(780),
    DeceivingBlade(781),
    AzmothCanyonProtectDeath1(782),
    AzmothCanyonProtectDeath2(783),
    AzmothCanyonProtectDeath3(784),
    AzmothCanyonProtectDeath4(785),
    KaringGoongiAdvantage(786),
    KaringDoolAdvantage(787),
    BaldrixHorsePenalty(788),
    BaldrixAcientGofPenalty(789),
    BaldrixSoulExecution(790),
    BossAggro(791),
    Confinement(792),
    GrabAndThrow(793),
    DarkCloud(794),
    FixedSpeedAndJump(795),
    UserAroundAttackDebuff(796),
    UserTrackingAreaWarning(797),
    RPEventStat(798),
    FlameOrbMultiAttack(799),
    SixthStormArrowEx(800),
    SuperFistEnrageStack(801),
    WildVulcanAdv(802),
    WildVulcanAdvStack(803),
    FlashSlashStack(804),
    RobotTransition(805),
    RobotTransitionRoboLuncherRM7(806),
    RobotTransitionMagneticField(807),
    RobotTransitionRoboFactory(808),
    NaturesBelief(809),
    LamourCarte(810),
    Joker(811),
    AdrenalinMaximum(812),
    LifeDeathControl(813),
    MissileBarrage(814),
    ForsakenRelic(815),
    Nightmare(816),
    LefPirateSpecterMark(817),
    RapidFire(818),
    ElementalFocus(819),
    SacredBastion(820),
    AzmothBossCDebuffImmun(821),
    TanjiroBeastBreathingType5(822),
    EnhanceInfernalBreath(823),
    EnhancePFResonance(824),
    RelicMaterialize(825),
    DslayerMetamorphosis(826),
    AdminWeaponMastery(827),
    RenPlumSword(828),
    RenPlumSwordForm3Stack(829),
    RenPlumSwordForm3Shoot(830),
    Sublimation(831),
    RenPlumSwordEx(832),
    SpiritAwakening(833),
    SpiritAwakeningStack(834),
    AuthenticDarkness(835),
    FrostBluster(836),
    TotalDAMr(837),
    GiantBossDeathCnt(838),
    SummonBomb(839),
    Unk840(840),
    PreventSlip(841),
    BladeStanceMode(842),
    BladeStancePower(843),
    KenjiCounter(844),
    EvasionMaster(845),
    Siksin(846),
    SelfHyperBodyIncPAD(847),
    SelfHyperBodyMaxHP(848),
    SelfHyperBodyMaxMP(849),
    BladeStanceBooster(850),
    Unk841(851),
    Unk842(852),
    EvasionUpgrade(853),
    CriticalBuffAdd(854),
    FoxBless(855),
    BossDamageRate(856),
    SkillDeployment(857),
    RepeatEffect2(858),
    NewPirateUnityOfPower(859),
    AntiEvilShield(860),
    ShamanMode(861),
    Chachacha(862),
    BearReviveOnce(863),
    Wet(864),
    Unk855(865),
    Unk856(866),
    Unk857(867),
    GrabbedByMob(868),
    WaterSmashTeam(869),
    WaterSmashClass(870),
    WaterSmashComboCount(871),
    WaterSmashBuffCount(872),
    SpecialTombPL(873),
    ReduceMP(874),
    KenjiShadowAttackBuff(875),
    Unk866(876),
    WorldExpBuff(877),
    WorldDropBuff(878),
    CurseRingBuff(879),
    SummonProp(880),
    GhostLiberationStack(881),
    Unk872(882),
    KannaSiksinAutoAttack(883),
    HowlingOfNature(884),
    ShamanModeChangeHyperBuff(885),
    MitsuhideDebuff(886),
    MitsuhideStigma(887),
    MitsuhideStackView(888),
    ShamanIgnoreTargetDEF(889),
    KannaFifthAttract(890),
    ShamanMapleShow(891),
    Unk882(892),
    HyperUpgradeDiscountR(893),
    KannaHakuHide(894),
    NeoTokyoBossThesis(895),
    NeoTokyoBossAntiThesis(896),
    NeoTokyoBossBomb(897),
    NeoTokyoBossPowOfLife(898),
    SixthHakuman(899),
    SixthShinBatto(900),
    KazaxDebuff(901),
    MarkingStella(902),
    RabbitStack(903),
    ShineMageStarlight(904),
    ShineMageAppear(905),
    ConstelEagle(906),
    ShineMageWitchHat(907),
    ConstelHornedWhelk(908), // 182111005
    ShineMageTrophy(909),
    ShineMageShine(910),
    ShineMageButterfly(911),
    ShineMageWolf(912),
    ShineMageWolfHowling(913),
    ShineMageCapella(914),
    ShineMageHourglass(915),
    ShineMageCircleOfSaviour(916),
    RideOrDieIncDropRate(917),
    PathFinderForceCompulsion(918),
    AnimaThiefTaoistUpgrade(919),
    AnimaThiefFlameStrike(920),
    BlasterFileBunker(921),
    AzmothItemBuffFinalDamR(922),
    ChampionRaidEnergy(923),
    RenLinkSkill(924),
    BaldrixWeakness(925),
    BaldrixWeaknessBlind(926),
    RenSpiritSwordExStack(927),

    DashSpeed(928),
    DashJump(929),
    RideVehicle(930),
    PartyBooster(931),
    GuidedBullet(932),
    Undead(933),
    RideVehicleExpire(934),
    RelicGauge(935),
    SecondAtomLockOn(936),

    ErdaStack(937),
    ErdaRevert(938),
    DescentOfSunRingType(939),
    MukHyunChosic(940),
    MukHyunDivine(941),
    MukHyunSingongCycle(942),
    MukHyun_SEON_PUNG_GAG(943),
    MukHyun_SEON_PUNG_GAG_COOL_TIME(944),
    MukHyun_HO_SIN_GANG_GI(945),
    MukHyunNoDivineDec(946),
    MukhyunLinkSkill(947),
    None(-1)
    ;
    public static final List<CharacterTemporaryStat> localOrders = Arrays.asList(ErdaStack, ErdaRevert, DescentOfSunRingType, MukHyunChosic, MukHyunDivine, MukHyunSingongCycle, MukHyun_SEON_PUNG_GAG, MukHyun_SEON_PUNG_GAG_COOL_TIME, MukHyun_HO_SIN_GANG_GI, MukHyunNoDivineDec, MukhyunLinkSkill, STR, INT, DEX, LUK, PAD, PDD, MAD, ACC, EVA, EVAR, Craft, Speed, Jump, EMHP, EMMP, EPAD, EMAD, EPDD, MagicGuard, DarkSight, Booster, PowerGuard, Guard, MaxHP, MaxMP, Invincible, SoulArrow, Stun, GravityConstraint, Shock, Poison, Seal, Darkness, ComboCounter, BlessedHammer, BlessedHammerActive, WeaponCharge, ElementalCharge, HolySymbol, MesoUp, ShadowPartner, ThiefSteal, PickPocket, BloodyExplosion, Thaw, Weakness, WeaknessMdamage, Curse, Slow, TimeBomb, BuffLimit, Team, DisOrder, Thread, Morph, Ghost, Regen, BasicStatUp, Stance, SharpEyes, ManaReflection, Attract, Magnet, MagnetArea, GuidedArrow, StraightForceAtomTargets, LefBuffMastery, TempSecondaryStat, CoalitionSupportSoldierStorm, LefMageLinkSkill, ShadowMomentum, NoBulletConsume, StackBuff, Trinity, Infinity, AdvancedBless, IllusionStep, Blind, Concentration, BanMap, MaxLevelBuff, Barrier, DojangShield, ReverseInput, MesoUpByItem, MesoAmountRate, MesoAmountRateRune, ItemUpByItem, RespectPImmune, RespectMImmune, DefenseAtt, DefenseState, DojangBerserk, DojangInvincible, SoulMasterFinal, WindBreakerFinal, Mortality, KarmaBlade, ElementalReset, HideAttack, EventRate, ComboAbilityBuff, ComboDrain, PartyBarrier, RepeatEffect, ExpBuffRate, StopPortion, StopMotion, Fear, MagicShield, MagicResistance, SoulStone, Flying, NewFlying, NaviFlying, Holding, Frozen, Frozen2, Web, Enrage, NotDamaged, FinalCut, HowlingAttackDamage, BeastForm, Dance, PinkbeanMinibeenMove, Sneak, Mechanic, DrawBack, BeastFormMaxHP, Dice, BlessingArmor, BlessingArmorIncPAD, DamR, TeleportMasteryOn, CombatOrders, Beholder, DispelItemOption, DispelItemOptionByField, Inflation, OnixDivineProtection, Bless, Explosion, DarkTornado, IncMaxHP, IncMaxMP, PVPDamage, PVPDamageSkill, PvPScoreBonus, PvPInvincible, PvPRaceEffect, HolyMagicShell, InfinityForce, AmplifyDamage, KeyDownTimeIgnore, MasterMagicOn, AsrR, AsrRByItem, TerR, DamAbsorbShield, Roulette, RouletteStack, Event, SpiritLink, CriticalBuff, DropRate, PlusExpRate, ItemInvincible, ItemCritical, ItemEvade, Event2, VampiricTouch, DDR, IncTerR, IncAsrR, DeathMark, PainMark, UsefulAdvancedBless, Lapidification, VampDeath, VampDeathSummon, VenomSnake, CarnivalAttack, CarnivalDefence, CarnivalExp, SlowAttack, PyramidEffect, HollowPointBullet, KeyDownMoving, KeyDownAreaMoving, CygnusElementSkill, IgnoreTargetDEF, StrikerElectricUsed, StrikerElectricStack, Invisible, ReviveOnce, AntiMagicShell, EnrageCr, EnrageCrDamMin, LifeTidal, Judgement, DojangLuckyBonus, HitCriDamR, Larkness, SmashStack, ReshuffleSwitch, SpecialAction, ArcaneAim, StopForceAtomInfo, SoulGazeCriDamR, SoulRageCount, PowerTransferGauge, AffinitySlug, SoulExalt, HiddenPieceOn, BossShield, MobZoneState, GiveMeHeal, TouchMe, Contagion, IgnoreAllCounter, IgnorePImmune, IgnoreAllImmune, IgnoreAllAbout, FinalJudgement, FireAura, VengeanceOfAngel, HeavensDoor, Preparation, BullsEye, IncEffectHPPotion, IncEffectMPPotion, SoulMP, FullSoulMP, SoulSkillDamageUp, BleedingToxin, IgnoreMobDamR, Asura, MegaSmasher, FlipTheCoin, UnityOfPower, Stimulate, ReturnTeleport, CapDebuff, DropRIncrease, IgnoreMobpdpR, BdR, Exceed, DiabolikRecovery, SurpassLimit, FinalAttackProp, ExceedOverload, DevilishPower, OverloadCount, BuckShot, FireBomb, HalfstatByDebuff, SurplusSupply, SetBaseDamage, AmaranthGenerator, StrikerHyperElectric, EventPointAbsorb, EventAssemble, StormBringer, ACCR, DEXR, Translucence, PoseType, CosmicForge, ElementSoul, CosmicOrb, GlimmeringTime, Restoration, ComboCostInc, TrueSight, CrossOverChain, ChillingStep, Reincarnation, ReincarnationMission, ReincarnationOnOff, DotBasedBuff, SixthDotBasedBuff, BlessEnsenble, QuiverCatridge, ExtraQuiverCatridge, ExtraQuiverMagic, ExtraQuiverVamp, UserControlMob, ImmuneBarrier, CriticalGrowing, LastUseSkillAttr, QuickDraw, BowMasterConcentration, ElementFlameBuff, TimeFastABuff, TimeFastBBuff, InfiniteResonance, GatherDropR, AimBox2D, CursorSniping, DebuffTolerance, TearsOfFairy, DotHealHPPerSecond, DotHealMPPerSecond, SpiritGuard, EunwolUnleashFoxOrb, PreReviveOnce, SetBaseDamageByBuff, LimitMP, ReflectDamR, ComboTempest, MHPCutR, MMPCutR, SelfWeakness, ElementDarkness, FlareTrick, FlameDischarge, Dominion, SiphonVitality, DarknessAscension, BossWaitingLinesBuff, DamageReduce, ShadowServant, ShadowIllusion, AddAttackCount, ComplusionSlant, JaguarSummoned, JaguarCount, SSFShootingAttack, DevilCry, ShieldAttack, DarkLighting, AttackCountX, BMageDeath, BombTime, NoDebuff, XenonAegisSystem, AngelicBursterSoulSeeker, EunwolFoxSpirit, NightWalkerBat, NightLordMark, WizardIgnite, Frenzy, ShadowSpear, BattlePvP_Helena_Mark, BattlePvP_Darklord_Explosion, BattlePvP_Helena_WindSpirit, BattlePvP_LangE_Protection, BattlePvP_LeeMalNyun_ScaleUp, BattlePvP_Revive, PinkbeanAttackBuff, RandAreaAttack, RandAreaAttack2, ShineRuneAttack, BattlePvP_Mike_Shield, BattlePvP_Mike_Bugle, PinkbeanRelax, PinkbeanYoYoStack, HowlingGaleStack, NextAttackEnhance, PirateDesire, AranCombotempastOption, ViperTimeLeap, RoyalGuardState, BodyRectGuardPrepare, MichaelSoulLink, MichaelStanceLink, TriflingWhimOnOff, AddRangeOnOff, KinesisPsychicPoint, KinesisPsychicOver, KinesisIncMastery, KinesisPsychicEnergeShield, BladeStance, DebuffActiveSkillHPCon, DebuffIncHP, BowMasterMortalBlow, AngelicBursterSoulResonance, Fever, RpSiksin, TeleportMasteryRange, FireBarrier, ChangeFoxMan, FixCoolTime, IncMobRateDummy, AdrenalinBoost, AranDrain, AranBoostEndHunt, RWCylinder, RWCombination, RWVulkanPunch, RWMagnumBlow, RWBarrier, RWBarrierHeal, RWMaximizeCannon, RWOverHeat, RWMovingEvar, Stigma, HeavensDoorNotTime, RuneStoneNoTime, EunwolSoulSeperateNotTime, XenonRocketRunch, TransformOverMan, EnergyBust, LightningUnion, BulletParty, LoadedDice, BishopPray, ChainArtsFury, MichaelFixDamDecTime, PinkbeanYoYoAddDamR, PairingUser, Warrior_AuraWeapon, Warrior_AuraWeaponStack, Wizard_OverloadMana, Michael_RhoAias, Kinesis_DustTornado, NightLord_SpreadThrow, CannonShooter_BFCannonBall, CannonShooter_MiniCannonBall, CannonShooter_RollingCannon, Shadower_ShadowAssault, CreateEventMeso, MesoRanger_MesoDizerX, FifthAdvWarriorShield, SplitArrow, FreudBlessing, OverloadMode, MastemaGuard, LefGloryWing, Elysion, OutSide, FifthSpotLight, RidingExpireInfoSave, WeaponVariety, Shadower_Assassination, ConvertAD, EtherealForm, ReadyToDie, Oblivion, Cr2CriDamR, BlackMageCreate, BlackMageDestroy, BlackMageMonochrome, HitStackDamR, NextSpecificSkillDamageUp, BuffControlDebuff, DispersionDamage, HarmonyLink, LefFastCharge, BuffIconNoShadow, CrystalChargeBuffIcon, LioMachinaCombineBuffIcon, CoalitionSupportWarplaneBuffIcon, BattlePvP_Ryude_Frozen, BattlePvP_Ryude_Buff, AntiMagicShellByJewelMaking, DamageRateSetUpForApc, SpecterGauge, SpecterMode, SpellBullet_Plain, SpellBullet_Scarlet, SpellBullet_Gust, SpellBullet_Abyss, ComingDeath, GreatOldAbyss, SixthPhoenix, HolyAdvent, ZodiacBurst, CombatFrenzy, LPSpellAmplification, LPInfinitySpell, LPMagicCircuitFullDrive, LPBattleMode, LPHoldSpecterGauge, DiscoveryWeather, BossWill_Infection, PvpApcTeam, HolyMagicShellReUse, StrikerComboStack, HeroComboInstinct, HeroAuraBladeStack, HeroAuraBladeAdv, HeroSongOfBlade, KhaliUltimatum, WindBreakerStormGuard, GrandCross, QuiverFullBurst, FlameWizardInfiniteFlame, SwordBaptism, MichaelSwordOfLight, PhantomMarkOfPhantomOwner, PhantomMarkOfPhantomTarget, WildGrenade, WildGrenadeSpark, ChainMantisADV, FieldGimmickFear, RescuedSoldierBuffIcon1, RescuedSoldierBuffIcon2, DropPer, ImmuneStun, FireBirdSupport, FireBirdSupportActive, AuraOfLife, MemoryOfJourney, DecBaseDamageDebuff, LimitConsumeDebuff, LimitEquipStatDebuff, BlackMageWeaponDestruction, BlackMageWeaponCreation, DestinyWeaponIndomitable, DestinyWeaponDecisive, BattlePvP_LangE_LiverStack, BattlePvP_Mike_Amor, SiphonVitalityBarrier, PathFinderAncientGuidance, BattlePvP_KeyDown, BattlePvP_Wongki_FlyingCharge, BattlePvP_Wongki_AwesomeFairy, BattlePvP_Mugong_PandaZone, BattleSurvivalDefence, BattleSurvivalInvincible, EventPvPDefence, EventPvPInvincible, EventSoccerBall, EventSoccerMomentBuff, ZeroDamageDebuff, FifthGoddessBless, CommonItemSkillContinuous, PinkbeanMatryoshka, NewtroWarriors, SilverMane, SilverManeBuff, BattlePVPAttBuff, MinigameStat, LuckyPapylus, AnimaThiefTaoistType, AnimaThiefTaoistGauge, AnimaThiefCloneAttack, AnimaThiefFifthCloneAttack, AnimaThiefButterfly, MiracleDrug, MiracleDrugNoCon, AnimaThiefMetaphysics, NoviceMagicianLink, NerotaPower, ChampionDoubleUp, LibraryMissionGuard, XenonHoloGramGraffiti, KeyDownEnable, DracoSlasherNoCooltime, WillOfSword, LWSwordGauge, LWCreation, LWDike, LWWonder, LWRestore, LefWarriorNobility, LWResonanceBuff, RunePurification, RuneContagion, DebuffHallucination, BMageAuraYellow, BMageAuraDrain, BMageAuraBlue, BMageAuraDark, BMageAuraDebuff, BMageAuraUnion, IceAura, KnightsAura, ZeroAuraStr, NovaArcherIncanation, AranComboTempestAura, XenonBursterLaser, AnimaThiefMetaphysicsBuff, RevenantGauge, DeathDance, ShadowShield, BMageAbyssalLightning, StrikerThunderChain, MercedesRoyalKnight, PhantomDefyingFate, FWSalamanderMischiefAttack, KinesisLawOfGravity, RepeatinCartrige, LefMageCrystalGate, ThrowBlasting, AnimaThiefIllusion, DarknessAura, WeaponVarietyFinale, Equinox, EquinoxActive, ZeroEgoWeaponAlpha, RelicUnboundD, RWAfterImage, NADragonGauge, NADragonEnchant, NADeathBlessing, NAThanatosDescent, NAAnnihilation, NARemainIncense, NAOminousStream, NABrutalPang, MobFlashBang, IgnorePriestDispel, LimitRecovery, NALinkSkill, StrikerChainReaction, LimitHealFactor, AdminCritical, AdminCriticalDam, AdminIgnoreTargetDEF, AdminBDR, AdminBuffTimeR, AdminActionSpeed, AdrenalinActivate, ATScrollPassive, YetiFuryGauge, YetiFuryMode, YetiMushroom, YetiMyFriendPepe, PinkbeanShowTime, YetiCook, PinkbeanCheer, DecFinalDamageDebuff, AMEarthVeinOnOff, AMPlanting, AMStoneShield, AMAbsorptionRiver, AMAbsorptionWind, AMAbsorptionSun, AMArtificialEarthVein, IgnoreFrictionOnOff, AnimaLotus, AMLinkSkill, AMEVTeleport, BossFieldFinalDamR, StormWhim, Anemoi, SeaSerpent, SerpentStone, SerpentScrew, Leviathan, FlameSweep, Cosmos, EnhancePiercing, BlasterFileBunker, EnhanceSniping, UltimateSniping, UltimatePiercing, EnhanceQuadrupleThrow, EnhanceHeadShot, UnwearyingRun, CrusaderPanic, IceAuraZone, HolyWater, EpicDungeonGauge, EpicDungeonMiddleBossBarrier, TriumphFeather, SixthAngelsRay, GrandFinale, WarInTheShade, FlashMirage, HolyBlood, OrbitalExplosion, DragonSlave, LimitBreakFinalAttack, TranscendentLight, SixthAssassination, SixthCovertShadowBuff, SixthAssassinationDarkSight, ArtificialEvolution, SixthFrozenLightning, KinesisUltimateBPM, ElementalKnight, LarknessStop, SummonChakri, SixthResonate, EnhanceNightLordFourSeasons, DarknessShuriken, ShadowAcceleration, ShadowBurst, DeceivingBlade, PathFinderForceCompulsion, AzmothCanyonProtectDeath1, AzmothCanyonProtectDeath2, AzmothCanyonProtectDeath3, AzmothCanyonProtectDeath4, KaringGoongiAdvantage, KaringDoolAdvantage, BaldrixHorsePenalty, BaldrixSoulExecution, BaldrixAcientGofPenalty, BossAggro, Confinement, FixedSpeedAndJump, GrabAndThrow, DarkCloud, UserAroundAttackDebuff, UserTrackingAreaWarning, RPEventStat, FlameOrbMultiAttack, AnimaThiefTaoistUpgrade, AnimaThiefFlameStrike, SixthStormArrowEx, SuperFistEnrageStack, WildVulcanAdv, WildVulcanAdvStack, SixthJavelinStack, SixthCrystalStack, FlashSlashStack, RobotTransition, RobotTransitionRoboLuncherRM7, RobotTransitionMagneticField, RobotTransitionRoboFactory, NaturesBelief, LamourCarte, Joker, AdrenalinMaximum, SixthGloryWingJavelinStack, LifeDeathControl, MissileBarrage, ForsakenRelic, Nightmare, LefPirateSpecterMark, RapidFire, ElementalFocus, SacredBastion, AzmothBossCDebuffImmun, AzmothItemBuffFinalDamR, TanjiroBeastBreathingType5, EnhanceInfernalBreath, EnhancePFResonance, RelicMaterialize, DslayerMetamorphosis, AdminWeaponMastery, ChampionRaidEnergy, RenLinkSkill, BaldrixWeakness, BaldrixWeaknessBlind, RenPlumSword, RenPlumSwordForm3Stack, RenPlumSwordForm3Shoot, RenSpiritSwordExStack, Sublimation, RenPlumSwordEx, SpiritAwakening, SpiritAwakeningStack, AuthenticDarkness, FrostBluster, TotalDAMr, IncMaxDamage, GiantBossDeathCnt, SummonBomb, PreventSlip, IndieAllSkill, BladeStanceMode, BladeStanceBooster, BladeStancePower, EvasionMaster, Siksin, SelfHyperBodyIncPAD, SelfHyperBodyMaxHP, SelfHyperBodyMaxMP, EvasionUpgrade, CriticalBuffAdd, FoxBless, BossDamageRate, SkillDeployment, RepeatEffect2, NewPirateUnityOfPower, AntiEvilShield, KenjiCounter, ShamanMode, Chachacha, BearReviveOnce, Wet, GrabbedByMob, WaterSmashTeam, WaterSmashClass, WaterSmashComboCount, WaterSmashBuffCount, SpecialTombPL, ReduceMP, KenjiShadowAttackBuff, WorldExpBuff, WorldDropBuff, CurseRingBuff, SummonProp, GhostLiberationStack, KannaSiksinAutoAttack, HowlingOfNature, ShamanModeChangeHyperBuff, CoronaBuffOverlap, MitsuhideDebuff, MitsuhideStigma, MitsuhideStackView, ShamanIgnoreTargetDEF, KannaFifthAttract, ShamanMapleShow, HyperUpgradeDiscountR, KannaHakuHide, NeoTokyoBossThesis, NeoTokyoBossAntiThesis, NeoTokyoBossBomb, NeoTokyoBossPowOfLife, SixthHakuman, SixthShinBatto, KazaxDebuff, MarkingStella, RabbitStack, ConstelHornedWhelk, ConstelEagle, ShineMageAppear, ShineMageWitchHat, ShineMageStarlight, ShineMageTrophy, ShineMageShine, ShineMageButterfly, ShineMageWolf, ShineMageWolfHowling, ShineMageCapella, ShineMageCircleOfSaviour, ShineMageHourglass, RideOrDieIncDropRate);

    final int bitPos;
    final int val;
    final int pos;
    public static final int length = 33;

    CharacterTemporaryStat(int val) {
        this.bitPos = val;
        this.val = 1 << (31 - bitPos % 32);
        this.pos = bitPos / 32;
    }

    public static CharacterTemporaryStat getByBitPos(int bitPos) {
        return Arrays.stream(values()).filter(v -> v.getBitPos() == bitPos).findAny().orElse(null);
    }

    public static CharacterTemporaryStat getByVal(int val) {
        return Arrays.stream(values()).filter(v -> v.getVal() == val).findAny().orElse(null);
    }

    public boolean isEncodeInt() {
        switch (this) {
            case CarnivalDefence:
            case SpiritLink:
            case DojangLuckyBonus:
            case SoulGazeCriDamR:
            case PowerTransferGauge:
            case ReturnTeleport:
            case ShadowPartner:
            case SetBaseDamage:
            case ImmuneBarrier:
            case QuiverCatridge:
            case NaviFlying:
            case Dance:
            case SetBaseDamageByBuff:
            case DotHealHPPerSecond:
            case DotHealMPPerSecond:
            case IncMaxDamage:
            case GrabbedByMob:
            case MarkingStella:
            case MagnetArea:
            case PairingUser:
            case MegaSmasher:
            case VampDeath:
            case FifthAdvWarriorShield:
            case RidingExpireInfoSave:
            case RWBarrier:
            case SiphonVitalityBarrier:
                return true;
            default:
                return false;
        }
    }

    public boolean isIndie() {
        return ordinal() < IndieStatCount.ordinal();
    }

    public int getVal() {
        return val;
    }

    public int getPos() {
        return pos;
    }

    public int getOrder() {
        return localOrders.indexOf(this);
    }

    public boolean isMovementAffectingStat() {
        switch (this) {
            case Speed:
            case Jump:
            case Stun:
            case Weakness:
            case Slow:
            case Morph:
            case Ghost:
            case BasicStatUp:
            case Attract:
            case RideVehicle:
            case RideVehicleExpire:
            case DashSpeed:
            case DashJump:
            case Flying:
            case Frozen:
            case Frozen2:
            case Lapidification:
            case IndieSpeed:
            case IndieJump:
            case KeyDownMoving:
            case Mechanic:
            case Magnet:
            case MagnetArea:
            case VampDeath:
            case VampDeathSummon:
            case GiveMeHeal:
            case DarkTornado:
            case NewFlying:
            case NaviFlying:
            case UserControlMob:
            case Dance:
            case SelfWeakness:
            case BattlePvP_Helena_WindSpirit:
            case IndieFlyAcc:
            case BattlePvP_LeeMalNyun_ScaleUp:
            case TouchMe:
            case IndieForceSpeed:
            case IndieForceJump:
            case BattlePvP_Ryude_Frozen:
            case BattlePvP_Ryude_Buff:
            case Frenzy:
            case ShadowSpear:
                //case BattlePvP_Wonky_ChargeA:
                //case BattlePvP_Wonky_Charge:
            case MinigameStat:
                return true;
            default:
                return false;
        }
    }

    public static final CharacterTemporaryStat[] isAuraCTS = new CharacterTemporaryStat[]{
            BishopPray,
            KnightsAura,
            MichaelSoulLink,
    };

    @Override
    public int compare(CharacterTemporaryStat o1, CharacterTemporaryStat o2) {
        if (o1.getPos() < o2.getPos()) {
            return -1;
        } else if (o1.getPos() > o2.getPos()) {
            return 1;
        }
        // hacky way to circumvent java not having unsigned ints
        int o1Val = o1.getVal();
        if (o1Val == 0x8000_0000) {
            o1Val = Integer.MAX_VALUE;
        }
        int o2Val = o2.getVal();
        if (o2Val == 0x8000_0000) {
            o2Val = Integer.MAX_VALUE;
        }

        if (o1Val > o2Val) {
            // bigger value = earlier in the int => smaller
            return -1;
        } else if (o1Val < o2Val) {
            return 1;
        }
        return 0;
    }

    public int getBitPos() {
        return bitPos;
    }
}