ALTER TABLE `characterstats` 
ADD COLUMN `combatpower` BIGINT NOT NULL DEFAULT 0,
ADD COLUMN `chuc` INT NOT NULL DEFAULT 0,
ADD COLUMN `arc` INT NOT NULL DEFAULT 0,
ADD COLUMN `aut` INT NOT NULL DEFAULT 0;
