-- ==============================================================================
-- Patch v265 Database Schema
-- Adds all missing columns required by SwordieMS v265 Java source code
-- ==============================================================================

USE `vietmaple`;

-- 1. accounts
ALTER TABLE `accounts`
ADD COLUMN IF NOT EXISTS `theme` INT NOT NULL DEFAULT 0;

-- 2. characterstats (in case not yet added)
ALTER TABLE `characterstats`
ADD COLUMN IF NOT EXISTS `combatpower` BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `chuc` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `arc` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `aut` INT NOT NULL DEFAULT 0;

-- 3. characters
ALTER TABLE `characters`
ADD COLUMN IF NOT EXISTS `decorationinventory` INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `medalid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `onlineTime` BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `onlineDay` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `deletionStartTime` BIGINT DEFAULT 0;

-- 4. items
ALTER TABLE `items`
ADD COLUMN IF NOT EXISTS `charid` INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `obtainedonce` TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS `bossrewardid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `mobtemplateid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `partysize` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `price` BIGINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `titleon` TINYINT(1) DEFAULT 0;

-- 5. equips
ALTER TABLE `equips`
ADD COLUMN IF NOT EXISTS `charid` INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `preset` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `equipattribute` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `soulitemid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_slot` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_str` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_dex` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_int` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_luk` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_pad` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_mad` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_pdd` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_hp` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_mp` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_speed` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_jump` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_allStatR` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_bossDamageR` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_damageR` SMALLINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `except_reduceReqLevel` SMALLINT DEFAULT 0;

-- 6. quests
ALTER TABLE `quests`
ADD COLUMN IF NOT EXISTS `charid` INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS `expireterm` DATETIME(3) DEFAULT NULL;

-- 7. keymaps
ALTER TABLE `keymaps`
ADD COLUMN IF NOT EXISTS `charid` INT NOT NULL DEFAULT 0;

-- 8. characterpotentials
ALTER TABLE `characterpotentials`
ADD COLUMN IF NOT EXISTS `preset` INT NOT NULL DEFAULT 0;

-- 9. beautydata
ALTER TABLE `beautydata`
ADD COLUMN IF NOT EXISTS `skinsize` INT NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS `skinstring` TEXT DEFAULT NULL;

-- 10. rewardinfo
ALTER TABLE `rewardinfo`
ADD COLUMN IF NOT EXISTS `starttime` DATETIME(3) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `endtime` DATETIME(3) NULL DEFAULT NULL;

-- 11. matrixskill
ALTER TABLE `matrixskill`
ADD COLUMN IF NOT EXISTS `lock` TINYINT(1) NOT NULL DEFAULT 0;

-- 12. guilds
ALTER TABLE `guilds`
ADD COLUMN IF NOT EXISTS `guildrank` INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `customemblem` BLOB DEFAULT NULL;

-- 13. auction_items
ALTER TABLE `auction_items`
ADD COLUMN IF NOT EXISTS `biduserid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `bidcharid` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `bidtime` DATETIME(3) DEFAULT NULL;

-- 14. auction_histories
ALTER TABLE `auction_histories`
ADD COLUMN IF NOT EXISTS `quantity` INT DEFAULT 1;

-- 15. petitems
ALTER TABLE `petitems`
ADD COLUMN IF NOT EXISTS `charid` INT DEFAULT NULL;
