package net.swordie.ms.enums;

public enum MessageType {
    DROP_PICKUP_MESSAGE(0),
    QUEST_RECORD_MESSAGE(1),
    CASH_ITEM_EXPIRE_MESSAGE(2),
    INC_EXP_MESSAGE(3),
    INC_SP_MESSAGE(4),
    INC_POP_MESSAGE(5),
    INC_MONEY_MESSAGE(6),
    INC_GP_MESSAGE(7),
    INC_COMMITMENT_MESSAGE(8),
    GIVE_BUFF_MESSAGE(9),
    GENERAL_ITEM_EXPIRE_MESSAGE(10),
    SYSTEM_MESSAGE(11),
    QUEST_RECORD_EX_MESSAGE(13),
    WORLD_SHARE_RECORD_MESSAGE(14),
    ITEM_PROTECT_EXPIRE_MESSAGE(15),
    ITEM_EXPIRE_REPLACE_MESSAGE(16),
    ITEM_ABILITY_TIME_LIMITED_EXPIRE_MESSAGE(17),
    SKILL_EXPIRE_MESSAGE(18),
    INC_NON_COMBAT_STAT_EXP_MESSAGE(19),
    LIMIT_NON_COMBAT_STAT_EXP_MESSAGE(21),
    ANDROID_MACHINE_HEART_ALSET_MESSAGE(23),
    INC_FATIGUE_BY_REST_MESSAGE(24),
    INC_PVP_POINT_MESSAGE(-1),
    PVP_ITEM_USE_MESSAGE(-1),
    WEDDING_PORTAL_ERROR(-1),
    INC_HARDCORE_EXP_MESSAGE(28),
    NOTICE_AUTO_LINE_CHANGED(29),
    ENTRY_RECORD_MESSAGE(-1),
    EVOLVING_SYSTEM_MESSAGE(-1),
    EVOLVING_SYSTEM_MESSAGE_WITH_NAME(-1),
    CORE_INVEN_OPERATION_MESSAGE(-1),
    NX_RECORD_MESSAGE(31),
    BLOCKED_BEHAVIOR_MESSAGE(-1),

    INC_WP_MESSAGE(35),
    MAX_WP_MESSAGE(36),

    STYLISH_KILL_MESSAGE(35),
    BARRIER_EFFECT_IGNORE_MESSAGE(36),
    EXPIRED_CASH_ITEM_RESULT_MESSAGE(37),
    COLLECTION_RECORD_MESSAGE(39),
    WHISPER_MESSAGE(42),

    ACHIEVEMENT_INIT(44),
    ACHIEVEMENT_DATA_MESSAGE(45),
    ACHIEVEMENT_RANK_MESSAGE(45),

    ;
    private final byte val;

    MessageType(int val) {
        this.val = (byte) val;
    }

    public byte getVal() {
        return val;
    }
}
